import type { LegalSection } from "@/components/marketing/legal-doc-layout";
import { LEGAL_ENTITY } from "@/lib/brand/legal";

/**
 * Terms of Service (EN). Convenience translation of the Polish Regulamin;
 * the Polish language version is the binding one. Section ids mirror pl.ts
 * so anchors stay stable across locales.
 */
export const TERMS_SECTIONS_EN: ReadonlyArray<LegalSection> = [
  {
    id: "postanowienia-ogolne",
    title: "§ 1. General provisions",
    content: `1. These Terms of Service set out the rules for providing services by electronic means through the tlumaczksef.pl website (the Service), in accordance with art. 8 of the Polish Act of 18 July 2002 on Providing Services by Electronic Means.
2. The Service is operated by ${LEGAL_ENTITY.name}, NIP (tax id): ${LEGAL_ENTITY.nip}, REGON: ${LEGAL_ENTITY.regon}, address: ${LEGAL_ENTITY.address} (the Operator).
3. You can contact the Operator at: ${LEGAL_ENTITY.contactEmail}.
4. The Terms are available free of charge on the Service before any agreement is concluded, in a form that allows downloading, storing, and printing.
5. This English text is a convenience translation. The Polish language version of the Terms (Regulamin) is the binding version.
6. Personal data processing is described in the Privacy Policy available on the Service.`
  },
  {
    id: "definicje",
    title: "§ 2. Definitions",
    content: `For the purposes of these Terms:
1. Service: the website available at tlumaczksef.pl together with its subpages.
2. User: a natural person with full legal capacity, a legal person, or an organizational unit with legal capacity using the Service.
3. Consumer: a User who is a natural person using the Service for purposes not directly related to their business or professional activity.
4. Sole trader with consumer rights: a natural person concluding a contract directly related to their business activity where the contract is not of a professional character for them.
5. Account: the set of resources in the Service assigned to the User's email address, created on first sign-in.
6. Source invoice: a structured invoice in XML format conforming to the FA(3) schema of the Polish Ministry of Finance, issued or received in the National e-Invoicing System (KSeF) and uploaded by the User to the Service.
7. Translation: a PDF document generated by the Service containing the content of a Source invoice translated into the selected language, including a bilingual version.
8. Credit: a settlement unit entitling the User to one Translation.
9. Package: a set of Credits purchased for a fee according to the price list available on the Service.`
  },
  {
    id: "rodzaje-uslug",
    title: "§ 3. Types and scope of services",
    content: `1. The Operator provides the following services by electronic means:
a) automatic translation of Source invoices into selected languages with PDF generation, including a bilingual version (Polish plus the target language), with the KSeF QR code preserved,
b) maintaining the Account, including Translation history and the Credit balance,
c) storing Source invoices and Translations for 30 days,
d) export of Account data in JSON format,
e) a free demo available without an Account, requiring one-time email verification.
2. The Service accepts only XML files conforming to the FA(3) schema. PDF files and other formats are not accepted as input.
3. The Service does not connect to the User's KSeF account and does not fetch invoices from KSeF on the User's behalf. The User uploads XML files to the Service themselves.
4. The field layout of the generated PDF follows the FA(3) schema of the Ministry of Finance, version 2025-06-25, and the KSeF QR code from the Source invoice is preserved.`
  },
  {
    id: "wymagania-techniczne",
    title: "§ 4. Technical requirements",
    content: `1. Using the Service requires:
a) a device with internet access,
b) a current version of a web browser with JavaScript and cookies enabled,
c) an active email address.
2. Sign-in is passwordless, via a one-time link sent to the User's email address. The sign-in link is valid for 60 minutes and can be used only once.
3. The Operator makes reasonable efforts to keep the Service working correctly in current versions of popular browsers. Correct operation in outdated or non-standard browsers is not guaranteed.`
  },
  {
    id: "konto",
    title: "§ 5. Account and conclusion of the agreement",
    content: `1. The agreement for providing services by electronic means in the scope of the Account is concluded at the moment of the first sign-in to the Service, which is equivalent to creating the Account.
2. Creating the Account requires accepting the Terms and reading the Privacy Policy. This information, together with links to both documents, is displayed on the sign-in page.
3. The Account agreement is concluded for an indefinite period. Maintaining the Account is free of charge.
4. One Account is assigned to one email address. The User must not give unauthorized persons access to their email inbox, as inbox access enables signing in to the Account.
5. The User must provide true and current data.`
  },
  {
    id: "cennik",
    title: "§ 6. Free allowance and Packages",
    content: `1. Every User with an Account is entitled to one free Translation in each calendar month. An unused free allowance does not carry over to the next month.
2. Further Translations are performed under paid Credit Packages. Package prices are set out in the price list. Prices are net amounts; 23% VAT is added.
3. Credits purchased in Packages do not expire and stack across purchases.
4. A Credit is consumed only after a Translation completes successfully. If a Translation fails for reasons attributable to the Service, no Credit is consumed.
5. Price list changes do not affect Packages already paid for.`
  },
  {
    id: "platnosci",
    title: "§ 7. Payments and invoices",
    content: `1. Payments for Packages are handled by the external payment operator Stripe (Stripe Payments Europe, Ltd., Ireland). The Operator does not store payment card data.
2. The agreement for delivery of a Package is concluded when the payment operator confirms the payment. Credits are added to the Account immediately after payment confirmation.
3. A VAT invoice is issued for every Package purchase. The invoice is issued electronically, submitted to the National e-Invoicing System (KSeF), and made available to the User via a link sent by email. By accepting the Terms the User consents to receiving invoices electronically.
4. For invoicing purposes the User provides the buyer's details: name, NIP (tax id), and address. The User is responsible for the correctness of these details.`
  },
  {
    id: "charakter-tlumaczen",
    title: "§ 8. Nature of Translations and disclaimers",
    content: `1. Translations are performed automatically, using artificial intelligence models provided by OpenAI and terminology dictionaries aligned with the FA(3) schema. Artificial intelligence models process only descriptive text fields (item names, units, descriptions, notes, footer). Amounts, bank account numbers, tax identification numbers (NIP and REGON), party names and addresses, invoice numbers, dates, currencies, and VAT rates are not sent to artificial intelligence models and are carried over without translation.
2. A Translation is an auxiliary, informational document. It is not a sworn or certified translation and does not replace one where the law requires a sworn translation.
3. A Translation does not modify the Source invoice issued in KSeF. The only accounting document remains the original structured invoice in KSeF.
4. The service does not constitute tax, legal, or accounting advice.
5. The User must verify the Translation before using it in business, in particular before sending it to a counterparty. Automatic translations may contain errors or inaccuracies.
6. The Service allows manual editing of selected Translation fields before the final PDF is generated. The User is responsible for the content of such edits.`
  },
  {
    id: "obowiazki",
    title: "§ 9. User obligations and prohibition of unlawful content",
    content: `1. Providing content of an unlawful nature is prohibited.
2. The User may upload only invoices they are authorized to process, in particular their own invoices or invoices received in the course of their business.
3. The following are prohibited: actions that may disrupt the Service, attempts at unauthorized access, automated bulk downloading of content, circumventing the demo or free allowance limits, and using the Service to process data in a way that infringes third-party rights.
4. In the event of a material breach of the Terms, the Operator may suspend or block the Account after first calling on the User to cease the breach, unless the nature of the breach requires immediate action. The User may appeal the decision by writing to the email address indicated in § 1.`
  },
  {
    id: "reklamacje",
    title: "§ 10. Complaints",
    content: `1. Complaints about the Service, including Translation quality and billing, can be submitted to: ${LEGAL_ENTITY.contactEmail}.
2. A complaint should include: the email address assigned to the Account, a description of the problem, and where possible the date of the event and the identifier of the Translation concerned.
3. The Operator handles complaints within 14 days of receipt and replies to the email address from which the complaint was sent.
4. For Consumers and sole traders with consumer rights, liability for the conformity of the digital service with the contract is governed by chapter 5b of the Polish Consumer Rights Act of 30 May 2014. In the event of non-conformity, the User may demand that conformity be restored and subsequently submit a statement on price reduction or withdrawal from the contract.`
  },
  {
    id: "odstapienie",
    title: "§ 11. Withdrawal and refunds",
    content: `1. A Consumer or a sole trader with consumer rights may withdraw from the agreement for delivery of a Package within 14 days of its conclusion without giving any reason. Sending the statement to the email address indicated in § 1 before the deadline is sufficient.
2. Starting to use Credits before the withdrawal deadline does not forfeit the right of withdrawal. In that case the refunded amount is reduced proportionally by the value of Credits used up to the moment of the statement.
3. Independently of statutory rights, every User, including businesses, may within 14 days of purchasing a Package request a refund of the part of the price proportional to the number of unused Credits.
4. Refunds are made within 14 days of receiving the statement, using the same payment method used for the purchase, unless the User expressly agrees to a different method.
5. The withdrawal statement may be made in any form, for example: "I withdraw from the agreement for delivery of the Package purchased on [date]. Account email: [address]". The statutory template attached as Annex 2 to the Polish Consumer Rights Act may also be used.
6. The User may terminate the free Account agreement at any time in accordance with § 12, which also covers the Consumer's right to withdraw from that agreement within 14 days of its conclusion.`
  },
  {
    id: "rozwiazanie",
    title: "§ 12. Term and termination",
    content: `1. The User may terminate the Account agreement at any time, without giving any reason, by deleting the Account in the Service settings or by sending a request to the email address indicated in § 1.
2. Deleting the Account permanently removes data in accordance with the Privacy Policy, including forfeiture of the unused free allowance. If unused Credits from a Package purchased within the last 14 days remain on the Account, the User may use the refund under § 11 before deleting the Account. Deleting the Account with Credits remaining after that period means resigning from their use.
3. The Operator may terminate the Account agreement for important reasons, such as: discontinuation of the Service, a change in law preventing further provision of services, or a material breach of the Terms by the User, with 14 days' notice sent to the User's email address.
4. If the Operator terminates the agreement for reasons not attributable to the User, the User is entitled to a refund of the price proportional to unused Credits, regardless of their purchase date.`
  },
  {
    id: "odpowiedzialnosc",
    title: "§ 13. Liability",
    content: `1. The Operator provides services with due care but does not guarantee uninterrupted availability of the Service. Planned maintenance breaks are announced in advance where possible.
2. The Operator is not liable for the content of Source invoices provided by the User or for the consequences of using a Translation that the User did not verify as required by § 8(5).
3. Towards Users who are neither Consumers nor sole traders with consumer rights, the Operator's liability is limited to the amount paid by the User for services in the 12 months preceding the event causing the damage and does not cover lost profits.
4. The liability limitations do not apply to Consumers or sole traders with consumer rights to the extent the law does not permit such limitation, nor to damage caused intentionally.`
  },
  {
    id: "dane-osobowe",
    title: "§ 14. Personal data and processing entrustment",
    content: `1. The Operator is the controller of the User's personal data (email address, billing data, technical data). Details are set out in the Privacy Policy.
2. Source invoices may contain personal data of third parties, in particular the User's counterparties (names, NIP numbers, addresses, bank account numbers). For this data the User remains the controller and the Operator acts as a processor within the meaning of art. 28 GDPR.
3. By accepting the Terms the User entrusts the Operator with processing personal data contained in Source invoices solely for the purpose and to the extent necessary to perform the services described in § 3, for the file retention period specified in § 3(1)(c).
4. The Operator undertakes to: process the entrusted data only on the User's documented instructions arising from the Terms, ensure confidentiality of authorized persons, apply appropriate technical and organizational measures (including encryption in transit and at rest and storing data on servers within the European Union), support the User in fulfilling obligations under art. 32-36 GDPR, and delete the entrusted data after the retention period.
5. The User gives general consent to sub-entrusting processing to the sub-processors listed in the Privacy Policy (in particular: Supabase, Vercel, OpenAI, Stripe, Resend, iFirma, Cloudflare). The Operator gives advance notice of intended changes to the sub-processor list, allowing the User to object.
6. The Operator does not use the content of Source invoices or Translations to train artificial intelligence models and does not share them with third parties other than sub-processors necessary to perform the service.`
  },
  {
    id: "zmiany",
    title: "§ 15. Changes to the Terms",
    content: `1. The Operator may amend the Terms for important reasons, such as: changes in law, changes to the scope or manner of providing services, security reasons, or the need to clarify provisions.
2. The Operator notifies Users with an Account of changes at least 14 days before they take effect, by email to the address assigned to the Account and by publishing the new version on the Service.
3. A User who does not accept the changes may terminate the agreement in accordance with § 12 before the changes take effect. Using the Service after that date constitutes acceptance of the new version.
4. Changes to the Terms do not affect acquired rights, in particular Credits already paid for.`
  },
  {
    id: "postanowienia-koncowe",
    title: "§ 16. Final provisions",
    content: `1. Agreements concluded under these Terms are governed by Polish law. The choice of law does not deprive a Consumer of the protection granted by mandatory provisions of the law of their habitual residence.
2. Disputes with Users who are not Consumers are resolved by the court competent for the Operator's registered office. Disputes with Consumers are resolved by the competent court under general rules.
3. A Consumer may use out-of-court complaint and redress procedures, including the assistance of a district (municipal) consumer ombudsman or a voivodeship inspector of the Trade Inspection. Details are available on the website of the Polish Office of Competition and Consumer Protection: uokik.gov.pl.
4. Should individual provisions of the Terms prove invalid or ineffective, the remaining provisions remain in force.
5. The Terms were drawn up in Polish. This English translation is provided for convenience; the Polish language version prevails.
6. The Terms apply from 2026-06-17.`
  }
];
