// Verbatim move of the bilingual copy dictionary previously inlined in app/page.tsx.
// Phase 2 lifts it here so the workspace component and the landing page can share strings.

export type UiLanguage = "pl" | "en";

export const copy = {
  pl: {
    navProduct: "Produkt",
    navHow: "Jak działa",
    navPricing: "Cennik",
    navFaq: "FAQ",
    uiLanguage: "Język interfejsu",
    badge: "Narzędzie dla polskich firm pracujących z KSeF",
    headline: "Tłumacz faktury KSeF na profesjonalne faktury dla zagranicznych kontrahentów.",
    subheadline:
      "Wgraj FA(3) XML albo PDF faktury KSeF, sprawdź czytelny podgląd, przetłumacz opisy i wyeksportuj estetyczny PDF bez logowania do KSeF, ERP ani systemu księgowego.",
    ctaUpload: "Wgraj fakturę",
    ctaHow: "Zobacz proces",
    trust1: "Nie wystawia faktur",
    trust2: "Nie łączy się z KSeF",
    trust3: "Nie zmienia danych finansowych",
    uploadTitle: "Wgraj KSeF FA(3) XML lub PDF",
    uploadHelp: "Przeciągnij plik tutaj albo wybierz z dysku.",
    parserFeature: "Parser FA(3) XML i PDF KSeF",
    translationFeature: "Tłumaczenia etykiet i opisów",
    pdfFeature: "Eksport PDF z polskimi znakami i QR",
    targetLanguage: "Język tłumaczenia faktury",
    bilingual: "Dwujęzycznie: wybrany język + polski",
    translate: "Tłumacz opisy",
    download: "Pobierz PDF",
    parsing: "Analizuję PDF KSeF...",
    empty: "Wgraj fakturę FA(3) XML lub PDF KSeF, aby wygenerować podgląd w języku",
    noAi:
      "Etykiety są tłumaczone słownikowo. Dodaj OPENAI_API_KEY, aby tłumaczyć opisy pozycji, jednostki, notatki i stopkę.",
    parsePdfFailed: "Nie udało się odczytać PDF.",
    translationFailed: "Tłumaczenie nie powiodło się.",
    pdfFailed: "Generowanie PDF nie powiodło się.",
    workspaceTitle: "Konwerter faktury",
    workspaceLead:
      "To główne narzędzie aplikacji. Wgraj plik, wybierz język kontrahenta, zdecyduj czy dokument ma być jedno- czy dwujęzyczny i pobierz gotowy PDF.",
    howTitle: "Jak korzystać",
    howLead: "Proces jest prosty i nie wymaga wdrożenia ani integracji.",
    steps: [
      ["Wgraj plik", "Obsługiwany jest XML FA(3) oraz wygenerowany PDF faktury KSeF."],
      ["Sprawdź podgląd", "Aplikacja normalizuje dane faktury do jednego modelu i pokazuje je w czytelnym układzie."],
      ["Przetłumacz treść", "Stałe etykiety pochodzą ze słowników, a AI tłumaczy tylko opisy, notatki i wolny tekst."],
      ["Pobierz PDF", "Eksport zawiera dane stron, pozycje, płatności, stopkę, QR KSeF i informację o reprezentacji tłumaczonej."]
    ],
    valueTitle: "Zaprojektowane pod komunikację z kontrahentami",
    valueLead:
      "To nie jest księgowość ani ERP. To wyspecjalizowane narzędzie do przygotowania zrozumiałej reprezentacji faktury dla odbiorcy zagranicznego.",
    values: [
      ["Bezpieczny zakres", "Nie wystawiamy, nie księgujemy i nie modyfikujemy faktury źródłowej."],
      ["Kontrola wartości", "Kwoty, daty, numery faktur, NIP, IBAN i stawki VAT nie są tłumaczone przez AI."],
      ["Europejskie języki", "Obsługa najważniejszych języków europejskich z możliwością szybkiego dodania kolejnych."],
      ["KSeF-ready", "Mapper obsługuje FA(3), faktury zaliczkowe, płatności, rachunki bankowe, stopkę i QR weryfikacyjny."]
    ],
    pricingTitle: "Cennik MVP",
    pricingLead: "Prosty model dla firm, które chcą szybko wysyłać czytelne faktury do partnerów zagranicznych.",
    plans: [
      ["Starter", "0 zł", "Testy i walidacja procesu", ["XML/PDF upload", "Podgląd faktury", "Eksport przykładowy", "Brak kont użytkowników"]],
      ["Business", "149 zł / mies.", "Dla zespołów sprzedaży i administracji", ["Nielimitowane tłumaczenia", "PDF z brandingiem", "Historia lokalna lub firmowa", "Priorytetowe języki UE"]],
      ["Enterprise", "Indywidualnie", "Dla organizacji z większym wolumenem", ["SLA i wdrożenie", "Polityki bezpieczeństwa", "Integracje wewnętrzne", "Dedykowane szablony PDF"]]
    ],
    faqTitle: "Najczęstsze pytania",
    faqs: [
      ["Czy aplikacja łączy się z KSeF?", "Nie. Użytkownik sam wgrywa XML lub PDF. Aplikacja tylko parsuje, tłumaczy, renderuje i eksportuje."],
      ["Czy to zastępuje księgowość?", "Nie. To czytelna reprezentacja faktury dla kontrahenta, a nie system księgowy."],
      ["Co tłumaczy AI?", "Wyłącznie wolny tekst: opisy pozycji, usług, notatki, stopkę i instrukcje płatnicze."],
      ["Czy kwoty lub numery mogą zostać zmienione?", "Nie powinny. Dane finansowe, identyfikatory, daty, waluty, IBAN i stawki VAT są przepisywane bez tłumaczenia AI."]
    ],
    seoTitle: "Tłumacz faktur KSeF, viewer FA(3), XML invoice to PDF",
    seoBody:
      "KSeF Invoice Translator pomaga polskim firmom przygotować profesjonalne tłumaczenie faktury KSeF dla kontrahenta. Narzędzie obsługuje FA(3) XML invoice, PDF z KSeF, Polish invoice translation, translate KSeF invoice oraz eksport invoice PDF dla partnerów międzynarodowych.",
    balanceFree: "Darmowy kredyt",
    balanceFreePaid: "kredytów",
    outOfCreditsTitle: "Brak kredytów",
    outOfCreditsBody:
      "Wykorzystałeś darmową fakturę w tym miesiącu i nie masz pakietu kredytów. Kup pakiet, aby kontynuować — pierwszy kredyt darmowy odnawia się 1. dnia każdego miesiąca.",
    buyCredits: "Kup pakiet",
    cancel: "Anuluj",
    close: "Zamknij",
    billingPlaceholderTitle: "Pakiety kredytów",
    billingPlaceholderBody: "Sklep z pakietami będzie dostępny w następnej fazie.",
    billingTitle: "Pakiety kredytów",
    billingSubtitle: "Pierwszy kredyt darmowy odnawia się 1. dnia każdego miesiąca. Kredyty z pakietów nie wygasają.",
    billingBandPaidLabel: "kredytów",
    billingBandFreeLabel: "darmowy w tym miesiącu",
    billingBandNextFreeLabel: "Następne darmowe odnowienie:",
    billingIncludedHeading: "Co dostajesz w cenie?",
    billingVatNote: "Wszystkie ceny netto. VAT 23% naliczany przy zakupie.",
    billingRefundPolicy: "Niewykorzystane kredyty nie wygasają. Zwroty na życzenie w 14 dni.",
    pickPackage: "Wybierz wielkość pakietu",
    unitPrice: "za fakturę (netto)",
    total: "Razem (netto)",
    totalWithTax: "Z 23% VAT",
    continueToCheckout: "Przejdź do płatności",
    purchaseHistory: "Historia zakupów",
    purchaseDate: "Data",
    purchaseSize: "Pakiet",
    purchaseTotal: "Kwota",
    purchaseStatus: "Status",
    purchaseStatusPaid: "Opłacony",
    purchaseStatusPending: "W toku",
    purchaseStatusFailed: "Nieudany",
    purchaseStatusRefunded: "Zwrócony",
    paymentSuccessTitle: "Płatność zakończona",
    paymentSuccessBody: "Kredyty zostały dodane do Twojego konta.",
    paymentCancelledTitle: "Płatność anulowana",
    paymentCancelledBody: "Płatność została anulowana. Możesz spróbować ponownie.",
    topUp: "Doładuj",
    creditsExhaustedShort: "Brak kredytów",
    lowBalanceBannerTitle: "Brak kredytów",
    lowBalanceBannerBody:
      "Wykorzystałeś darmową fakturę w tym miesiącu i nie masz pakietu kredytów. Kup pakiet, aby przesłać kolejną fakturę.",
    newInvoice: "Nowa faktura",
    recentHeading: "Ostatnie",
    allArchive: "Cały archiwum",
    helpLabel: "Pomoc",
    contactLabel: "Kontakt",
    tryWithSample: "Spróbuj z przykładową fakturą",
    onboardingTitle: "Co dostajesz",
    onboardingItem1: "1 darmowa faktura w miesiącu",
    onboardingItem2: "Tłumaczenie do 20+ języków",
    onboardingItem3: "Dwujęzyczny PDF z kodem QR KSeF",
    onboardingItem4: "Bez logowania do KSeF, bez integracji",
    cached: "zapisane",
    moreLanguages: "Więcej języków",
    originalPolish: "Polski",
    accountTitle: "Konto",
    accountProfileHeading: "Profil",
    accountEmailLabel: "E-mail",
    accountEmailHelp: "E-mail logowania nie można zmienić.",
    accountLocaleLabel: "Język interfejsu",
    accountDisplayNameLabel: "Nazwa wyświetlana (opcjonalnie)",
    accountDisplayNameHelp: "Używana w transakcyjnych e-mailach.",
    accountSaveButton: "Zapisz zmiany",
    accountSavingButton: "Zapisuję…",
    accountSaveSuccess: "Zapisano.",
    accountSaveError: "Nie udało się zapisać zmian.",
    accountExportHeading: "Eksport danych (RODO)",
    accountExportBody: "Pobierz pełny eksport swoich danych w formacie JSON.",
    accountExportButton: "Pobierz dane (JSON)",
    accountExportPreparing: "Przygotowuję…",
    accountDangerHeading: "Strefa niebezpieczna",
    accountDeleteAccountTitle: "Usuń konto",
    accountDeleteAccountBody: "Wszystkie twoje dane (faktury, tłumaczenia, historia zakupów) zostaną trwale usunięte.",
    accountDeleteAccountButton: "Usuń konto",
    accountDeleteConfirmTitle: "Potwierdź usunięcie konta",
    accountDeleteConfirmBody: "Wpisz swój adres e-mail, aby potwierdzić. Tej operacji nie można cofnąć.",
    accountDeleteConfirmPlaceholder: "Wpisz adres e-mail",
    accountDeleteConfirmAction: "Tak, usuń trwale moje konto",
    accountDeleteCancel: "Anuluj"
  },
  en: {
    navProduct: "Product",
    navHow: "How it works",
    navPricing: "Pricing",
    navFaq: "FAQ",
    uiLanguage: "Interface language",
    badge: "Utility for Polish companies working with KSeF",
    headline: "Translate KSeF invoices into professional invoices for international contractors.",
    subheadline:
      "Upload FA(3) XML or a rendered KSeF PDF, review a readable invoice, translate free text, and export a polished PDF without KSeF login, ERP, or accounting workflows.",
    ctaUpload: "Upload invoice",
    ctaHow: "See workflow",
    trust1: "Does not issue invoices",
    trust2: "Does not connect to KSeF",
    trust3: "Does not alter financial data",
    uploadTitle: "Upload KSeF FA(3) XML or PDF",
    uploadHelp: "Drag and drop, or choose a file from your computer.",
    parserFeature: "FA(3) XML and KSeF PDF parser",
    translationFeature: "Label and free-text translation",
    pdfFeature: "Unicode PDF export with QR",
    targetLanguage: "Invoice target language",
    bilingual: "Bilingual: selected language + Polish",
    translate: "Translate descriptions",
    download: "Download PDF",
    parsing: "Parsing KSeF PDF...",
    empty: "Upload a FA(3) XML or KSeF PDF invoice to generate the preview in",
    noAi:
      "Static labels are translated from dictionaries. Add OPENAI_API_KEY to translate item descriptions, units, notes, and footer text.",
    parsePdfFailed: "PDF parsing failed.",
    translationFailed: "Translation failed.",
    pdfFailed: "PDF generation failed.",
    workspaceTitle: "Invoice converter",
    workspaceLead:
      "This is the application workspace. Upload a file, select the contractor language, choose mono- or bilingual output, and export the PDF.",
    howTitle: "How it works",
    howLead: "A focused workflow with no deployment or integration required.",
    steps: [
      ["Upload file", "FA(3) XML and rendered KSeF invoice PDFs are supported."],
      ["Review preview", "The app normalizes invoice data into one internal model and renders it clearly."],
      ["Translate text", "Fixed labels use dictionaries; AI translates only descriptions, notes, and free text."],
      ["Export PDF", "The export includes parties, line items, payment, footer, KSeF QR, and translation disclaimer."]
    ],
    valueTitle: "Built for contractor communication",
    valueLead:
      "This is not accounting or ERP software. It is a focused utility for readable invoice representations for foreign recipients.",
    values: [
      ["Safe scope", "We do not issue, book, or modify the source invoice."],
      ["Value control", "Amounts, dates, invoice numbers, VAT IDs, IBANs, and VAT rates are never translated by AI."],
      ["European languages", "Major European languages are supported and more can be added centrally."],
      ["KSeF-ready", "The mapper handles FA(3), advances, payments, bank accounts, footers, and verification QR links."]
    ],
    pricingTitle: "MVP pricing",
    pricingLead: "A simple model for companies sending readable invoices to foreign partners.",
    plans: [
      ["Starter", "€0", "Testing and validation", ["XML/PDF upload", "Invoice preview", "Sample export", "No user accounts"]],
      ["Business", "€35 / mo", "For sales and administration teams", ["Unlimited translations", "Branded PDFs", "Local or company history", "Priority EU languages"]],
      ["Enterprise", "Custom", "For larger invoice volumes", ["SLA and onboarding", "Security policies", "Internal integrations", "Custom PDF templates"]]
    ],
    faqTitle: "FAQ",
    faqs: [
      ["Does it connect to KSeF?", "No. Users upload XML or PDF files. The app only parses, translates, renders, and exports."],
      ["Does it replace accounting?", "No. It creates a readable representation for contractors, not bookkeeping records."],
      ["What does AI translate?", "Only free text: line item descriptions, service names, notes, footer, and payment instructions."],
      ["Can amounts or identifiers change?", "They should not. Financial values, IDs, dates, currencies, IBANs, and VAT rates are copied, not translated by AI."]
    ],
    seoTitle: "KSeF invoice translator, FA(3) viewer, XML invoice to PDF",
    seoBody:
      "KSeF Invoice Translator helps Polish companies prepare professional KSeF invoice translations for contractors. It supports FA(3) XML invoice files, KSeF PDFs, Polish invoice translation, translate KSeF invoice workflows, and invoice PDF export for international partners.",
    balanceFree: "Free credit",
    balanceFreePaid: "credits",
    outOfCreditsTitle: "Out of credits",
    outOfCreditsBody:
      "You have used your free invoice for this month and have no credit pack. Buy a pack to continue — the free credit refreshes on the 1st of each month.",
    buyCredits: "Buy credits",
    cancel: "Cancel",
    close: "Close",
    billingPlaceholderTitle: "Credit packs",
    billingPlaceholderBody: "The credit-pack store will be available in the next phase.",
    billingTitle: "Credit packs",
    billingSubtitle: "The free credit refreshes on the 1st of each month. Pack credits never expire.",
    billingBandPaidLabel: "credits",
    billingBandFreeLabel: "free this month",
    billingBandNextFreeLabel: "Next free credit refreshes:",
    billingIncludedHeading: "What's included?",
    billingVatNote: "All prices net of VAT. 23% VAT added at checkout.",
    billingRefundPolicy: "Unused credits never expire. Refunds on request within 14 days.",
    pickPackage: "Pick a pack size",
    unitPrice: "per invoice (net)",
    total: "Total (net)",
    totalWithTax: "With 23% VAT",
    continueToCheckout: "Continue to checkout",
    purchaseHistory: "Purchase history",
    purchaseDate: "Date",
    purchaseSize: "Pack",
    purchaseTotal: "Amount",
    purchaseStatus: "Status",
    purchaseStatusPaid: "Paid",
    purchaseStatusPending: "Pending",
    purchaseStatusFailed: "Failed",
    purchaseStatusRefunded: "Refunded",
    paymentSuccessTitle: "Payment complete",
    paymentSuccessBody: "Credits have been added to your account.",
    paymentCancelledTitle: "Payment cancelled",
    paymentCancelledBody: "The payment was cancelled. You can try again.",
    topUp: "Top up",
    creditsExhaustedShort: "Out of credits",
    lowBalanceBannerTitle: "Out of credits",
    lowBalanceBannerBody:
      "You have used your free invoice this month and have no credit pack. Buy a pack to upload another invoice.",
    newInvoice: "New invoice",
    recentHeading: "Recent",
    allArchive: "Full archive",
    helpLabel: "Help",
    contactLabel: "Contact",
    tryWithSample: "Try with sample invoice",
    onboardingTitle: "What you get",
    onboardingItem1: "1 free invoice per month",
    onboardingItem2: "Translation to 20+ languages",
    onboardingItem3: "Bilingual PDF with KSeF QR",
    onboardingItem4: "No KSeF login, no integration required",
    cached: "cached",
    moreLanguages: "More languages",
    originalPolish: "Polish",
    accountTitle: "Account",
    accountProfileHeading: "Profile",
    accountEmailLabel: "Email",
    accountEmailHelp: "Sign-in email cannot be changed.",
    accountLocaleLabel: "Interface language",
    accountDisplayNameLabel: "Display name (optional)",
    accountDisplayNameHelp: "Used in transactional emails.",
    accountSaveButton: "Save changes",
    accountSavingButton: "Saving…",
    accountSaveSuccess: "Saved.",
    accountSaveError: "Could not save changes.",
    accountExportHeading: "Data export (GDPR)",
    accountExportBody: "Download a full export of your data in JSON format.",
    accountExportButton: "Download data (JSON)",
    accountExportPreparing: "Preparing…",
    accountDangerHeading: "Danger zone",
    accountDeleteAccountTitle: "Delete account",
    accountDeleteAccountBody: "All your data (invoices, translations, purchase history) will be permanently deleted.",
    accountDeleteAccountButton: "Delete account",
    accountDeleteConfirmTitle: "Confirm account deletion",
    accountDeleteConfirmBody: "Type your email address to confirm. This action cannot be undone.",
    accountDeleteConfirmPlaceholder: "Type your email address",
    accountDeleteConfirmAction: "Yes, permanently delete my account",
    accountDeleteCancel: "Cancel"
  }
} satisfies Record<UiLanguage, Record<string, unknown>>;

export type Copy = (typeof copy)[UiLanguage];
