import type { LanguageCode, TranslationLabels } from "@/types/invoice";

export const localizedLabels: Partial<Record<LanguageCode, Partial<TranslationLabels>>> = {
  nl: {
    invoice: "Factuur", invoiceType: "Factuurtype", invoiceTypeBasic: "Basisfactuur", invoiceTypeAdvance: "Voorschotfactuur", invoiceTypeFinal: "Eindafrekening", invoiceTypeCorrection: "Correctiefactuur", invoiceNumber: "Factuurnummer", issueDate: "Uitgiftedatum", saleDate: "Verkoopdatum", currency: "Valuta", seller: "Verkoper", buyer: "Koper", vatId: "Btw-nummer", address: "Adres", description: "Omschrijving", quantity: "Aantal", unit: "Eenheid", unitPrice: "Eenheidsprijs", vatRate: "Btw-tarief", netValue: "Nettowaarde", grossValue: "Brutowaarde", netTotal: "Netto totaal", vatTotal: "Btw totaal", grossTotal: "Bruto totaal", payment: "Betaling", paymentTerms: "Betalingsvoorwaarden", partialPayments: "Deelbetalingen", paid: "Betaald", paidDate: "Betaaldatum", amount: "Bedrag", taxSummary: "Btw-overzicht", bankAccounts: "Bankrekeningen", factorBankAccounts: "Factorbankrekeningen", bankName: "Banknaam", accountNumber: "Rekeningnummer", accountDescription: "Rekeningomschrijving", dueDate: "Vervaldatum", method: "Methode", bankAccount: "Bankrekening", notes: "Notities", additionalInformation: "Aanvullende informatie", line: "Regel", key: "Sleutel", value: "Waarde", thirdParties: "Aanvullende partijen", authorizedParty: "Gemachtigde partij", settlements: "Verrekeningen", charges: "Toeslagen", deductions: "Aftrekken", reason: "Reden", amountToSettle: "Te verrekenen bedrag", transactionTerms: "Transactievoorwaarden", orders: "Bestellingen", orderNumber: "Bestelnummer", contractNumber: "Contractnummer", totalValue: "Totale waarde", verification: "KSeF-verificatie", ksefNumber: "KSeF-nummer", verificationLink: "Verificatielink", footer: "Voettekst", registry: "Registratiegegevens", translatedRepresentation: "Dit document is een vertaalde, leesbare weergave van een Poolse gestructureerde KSeF-factuur.", originalPolish: "Pools origineel", translated: "Vertaling"
  },
  pt: {
    invoice: "Fatura", invoiceType: "Tipo de fatura", invoiceTypeBasic: "Fatura básica", invoiceTypeAdvance: "Fatura de adiantamento", invoiceTypeFinal: "Fatura final", invoiceTypeCorrection: "Fatura retificativa", invoiceNumber: "Número da fatura", issueDate: "Data de emissão", saleDate: "Data de venda", currency: "Moeda", seller: "Vendedor", buyer: "Comprador", vatId: "NIF / IVA", address: "Endereço", description: "Descrição", quantity: "Quantidade", unit: "Unidade", unitPrice: "Preço unitário", vatRate: "Taxa de IVA", netValue: "Valor líquido", grossValue: "Valor bruto", netTotal: "Total líquido", vatTotal: "IVA total", grossTotal: "Total bruto", payment: "Pagamento", paymentTerms: "Condições de pagamento", partialPayments: "Pagamentos parciais", paid: "Pago", paidDate: "Data de pagamento", amount: "Montante", taxSummary: "Resumo do IVA", bankAccounts: "Contas bancárias", factorBankAccounts: "Contas bancárias do fator", bankName: "Nome do banco", accountNumber: "Número da conta", accountDescription: "Descrição da conta", dueDate: "Data de vencimento", method: "Método", bankAccount: "Conta bancária", notes: "Notas", additionalInformation: "Informações adicionais", line: "Linha", key: "Chave", value: "Valor", thirdParties: "Partes adicionais", authorizedParty: "Parte autorizada", settlements: "Liquidações", charges: "Encargos", deductions: "Deduções", reason: "Motivo", amountToSettle: "Montante a liquidar", transactionTerms: "Condições da transação", orders: "Encomendas", orderNumber: "Número da encomenda", contractNumber: "Número do contrato", totalValue: "Valor total", verification: "Verificação KSeF", ksefNumber: "Número KSeF", verificationLink: "Link de verificação", footer: "Rodapé", registry: "Dados de registo", translatedRepresentation: "Este documento é uma representação traduzida e legível de uma fatura estruturada polaca KSeF.", originalPolish: "Original polaco", translated: "Tradução"
  },
  cs: {
    invoice: "Faktura", invoiceType: "Typ faktury", invoiceTypeBasic: "Základní faktura", invoiceTypeAdvance: "Zálohová faktura", invoiceTypeFinal: "Konečná zúčtovací faktura", invoiceTypeCorrection: "Opravná faktura", invoiceNumber: "Číslo faktury", issueDate: "Datum vystavení", saleDate: "Datum prodeje", currency: "Měna", seller: "Prodávající", buyer: "Kupující", vatId: "DIČ", address: "Adresa", description: "Popis", quantity: "Množství", unit: "Jednotka", unitPrice: "Jednotková cena", vatRate: "Sazba DPH", netValue: "Čistá hodnota", grossValue: "Hrubá hodnota", netTotal: "Čistý součet", vatTotal: "DPH celkem", grossTotal: "Hrubý součet", payment: "Platba", paymentTerms: "Platební podmínky", partialPayments: "Částečné platby", paid: "Zaplaceno", paidDate: "Datum platby", amount: "Částka", taxSummary: "Souhrn DPH", bankAccounts: "Bankovní účty", factorBankAccounts: "Bankovní účty faktora", bankName: "Název banky", accountNumber: "Číslo účtu", accountDescription: "Popis účtu", dueDate: "Datum splatnosti", method: "Metoda", bankAccount: "Bankovní účet", notes: "Poznámky", additionalInformation: "Dodatečné informace", line: "Řádek", key: "Klíč", value: "Hodnota", thirdParties: "Další strany", authorizedParty: "Oprávněná strana", settlements: "Vyúčtování", charges: "Příplatky", deductions: "Odpočty", reason: "Důvod", amountToSettle: "Částka k vyúčtování", transactionTerms: "Podmínky transakce", orders: "Objednávky", orderNumber: "Číslo objednávky", contractNumber: "Číslo smlouvy", totalValue: "Celková hodnota", verification: "Ověření KSeF", ksefNumber: "Číslo KSeF", verificationLink: "Ověřovací odkaz", footer: "Zápatí", registry: "Registrační údaje", translatedRepresentation: "Tento dokument je přeloženou, čitelnou reprezentací polské strukturované faktury KSeF.", originalPolish: "Polský originál", translated: "Překlad"
  },
  sk: {
    invoice: "Faktúra", invoiceType: "Typ faktúry", invoiceTypeBasic: "Základná faktúra", invoiceTypeAdvance: "Zálohová faktúra", invoiceTypeFinal: "Konečná zúčtovacia faktúra", invoiceTypeCorrection: "Opravná faktúra", invoiceNumber: "Číslo faktúry", issueDate: "Dátum vystavenia", saleDate: "Dátum predaja", currency: "Mena", seller: "Predávajúci", buyer: "Kupujúci", vatId: "IČ DPH", address: "Adresa", description: "Popis", quantity: "Množstvo", unit: "Jednotka", unitPrice: "Jednotková cena", vatRate: "Sadzba DPH", netValue: "Čistá hodnota", grossValue: "Hrubá hodnota", netTotal: "Čistý súčet", vatTotal: "DPH spolu", grossTotal: "Hrubý súčet", payment: "Platba", paymentTerms: "Platobné podmienky", partialPayments: "Čiastočné platby", paid: "Zaplatené", paidDate: "Dátum platby", amount: "Suma", taxSummary: "Súhrn DPH", bankAccounts: "Bankové účty", factorBankAccounts: "Bankové účty faktora", bankName: "Názov banky", accountNumber: "Číslo účtu", accountDescription: "Popis účtu", dueDate: "Dátum splatnosti", method: "Spôsob", bankAccount: "Bankový účet", notes: "Poznámky", additionalInformation: "Dodatočné informácie", line: "Riadok", key: "Kľúč", value: "Hodnota", thirdParties: "Ďalšie strany", authorizedParty: "Oprávnená strana", settlements: "Vyúčtovania", charges: "Príplatky", deductions: "Odpočty", reason: "Dôvod", amountToSettle: "Suma na vyúčtovanie", transactionTerms: "Podmienky transakcie", orders: "Objednávky", orderNumber: "Číslo objednávky", contractNumber: "Číslo zmluvy", totalValue: "Celková hodnota", verification: "Overenie KSeF", ksefNumber: "Číslo KSeF", verificationLink: "Overovací odkaz", footer: "Päta", registry: "Registračné údaje", translatedRepresentation: "Tento dokument je preloženou, čitateľnou reprezentáciou poľskej štruktúrovanej faktúry KSeF.", originalPolish: "Poľský originál", translated: "Preklad"
  },
  hu: {
    invoice: "Számla", invoiceType: "Számlatípus", invoiceTypeBasic: "Alapszámla", invoiceTypeAdvance: "Előlegszámla", invoiceTypeFinal: "Végelszámoló számla", invoiceTypeCorrection: "Helyesbítő számla", invoiceNumber: "Számlaszám", issueDate: "Kiállítás dátuma", saleDate: "Értékesítés dátuma", currency: "Pénznem", seller: "Eladó", buyer: "Vevő", vatId: "Adószám", address: "Cím", description: "Leírás", quantity: "Mennyiség", unit: "Egység", unitPrice: "Egységár", vatRate: "ÁFA-kulcs", netValue: "Nettó érték", grossValue: "Bruttó érték", netTotal: "Nettó összesen", vatTotal: "ÁFA összesen", grossTotal: "Bruttó összesen", payment: "Fizetés", paymentTerms: "Fizetési feltételek", partialPayments: "Részfizetések", paid: "Fizetve", paidDate: "Fizetés dátuma", amount: "Összeg", taxSummary: "ÁFA-összesítő", bankAccounts: "Bankszámlák", factorBankAccounts: "Faktor bankszámlák", bankName: "Bank neve", accountNumber: "Számlaszám", accountDescription: "Számla leírása", dueDate: "Esedékesség", method: "Mód", bankAccount: "Bankszámla", notes: "Megjegyzések", additionalInformation: "További információk", line: "Sor", key: "Kulcs", value: "Érték", thirdParties: "További felek", authorizedParty: "Meghatalmazott fél", settlements: "Elszámolások", charges: "Terhelések", deductions: "Levonások", reason: "Ok", amountToSettle: "Elszámolandó összeg", transactionTerms: "Tranzakciós feltételek", orders: "Rendelések", orderNumber: "Rendelésszám", contractNumber: "Szerződésszám", totalValue: "Teljes érték", verification: "KSeF-ellenőrzés", ksefNumber: "KSeF-szám", verificationLink: "Ellenőrző link", footer: "Lábléc", registry: "Cégnyilvántartási adatok", translatedRepresentation: "Ez a dokumentum egy lengyel KSeF strukturált számla lefordított, ember által olvasható megjelenítése.", originalPolish: "Lengyel eredeti", translated: "Fordítás"
  },
  ro: {
    invoice: "Factură", invoiceType: "Tip factură", invoiceTypeBasic: "Factură de bază", invoiceTypeAdvance: "Factură de avans", invoiceTypeFinal: "Factură finală", invoiceTypeCorrection: "Factură corectivă", invoiceNumber: "Număr factură", issueDate: "Data emiterii", saleDate: "Data vânzării", currency: "Monedă", seller: "Vânzător", buyer: "Cumpărător", vatId: "Cod TVA", address: "Adresă", description: "Descriere", quantity: "Cantitate", unit: "Unitate", unitPrice: "Preț unitar", vatRate: "Cotă TVA", netValue: "Valoare netă", grossValue: "Valoare brută", netTotal: "Total net", vatTotal: "TVA totală", grossTotal: "Total brut", payment: "Plată", paymentTerms: "Condiții de plată", partialPayments: "Plăți parțiale", paid: "Plătit", paidDate: "Data plății", amount: "Sumă", taxSummary: "Rezumat TVA", bankAccounts: "Conturi bancare", factorBankAccounts: "Conturi bancare factor", bankName: "Numele băncii", accountNumber: "Număr cont", accountDescription: "Descriere cont", dueDate: "Data scadenței", method: "Metodă", bankAccount: "Cont bancar", notes: "Note", additionalInformation: "Informații suplimentare", line: "Linie", key: "Cheie", value: "Valoare", thirdParties: "Părți suplimentare", authorizedParty: "Parte autorizată", settlements: "Decontări", charges: "Taxe", deductions: "Deduceri", reason: "Motiv", amountToSettle: "Sumă de decontat", transactionTerms: "Condiții tranzacție", orders: "Comenzi", orderNumber: "Număr comandă", contractNumber: "Număr contract", totalValue: "Valoare totală", verification: "Verificare KSeF", ksefNumber: "Număr KSeF", verificationLink: "Link verificare", footer: "Subsol", registry: "Date de înregistrare", translatedRepresentation: "Acest document este o reprezentare tradusă și lizibilă a unei facturi structurate poloneze KSeF.", originalPolish: "Original polonez", translated: "Traducere"
  },
  bg: {
    invoice: "Фактура", invoiceType: "Тип фактура", invoiceTypeBasic: "Основна фактура", invoiceTypeAdvance: "Авансова фактура", invoiceTypeFinal: "Окончателна фактура", invoiceTypeCorrection: "Коригираща фактура", invoiceNumber: "Номер на фактура", issueDate: "Дата на издаване", saleDate: "Дата на продажба", currency: "Валута", seller: "Продавач", buyer: "Купувач", vatId: "ДДС номер", address: "Адрес", description: "Описание", quantity: "Количество", unit: "Единица", unitPrice: "Единична цена", vatRate: "Ставка ДДС", netValue: "Нетна стойност", grossValue: "Брутна стойност", netTotal: "Общо нето", vatTotal: "Общо ДДС", grossTotal: "Общо бруто", payment: "Плащане", paymentTerms: "Условия за плащане", partialPayments: "Частични плащания", paid: "Платено", paidDate: "Дата на плащане", amount: "Сума", taxSummary: "Обобщение на ДДС", bankAccounts: "Банкови сметки", factorBankAccounts: "Банкови сметки на фактор", bankName: "Име на банка", accountNumber: "Номер на сметка", accountDescription: "Описание на сметка", dueDate: "Падеж", method: "Метод", bankAccount: "Банкова сметка", notes: "Бележки", additionalInformation: "Допълнителна информация", line: "Ред", key: "Ключ", value: "Стойност", thirdParties: "Допълнителни страни", authorizedParty: "Упълномощена страна", settlements: "Разчети", charges: "Начисления", deductions: "Удръжки", reason: "Причина", amountToSettle: "Сума за уреждане", transactionTerms: "Условия на транзакцията", orders: "Поръчки", orderNumber: "Номер на поръчка", contractNumber: "Номер на договор", totalValue: "Обща стойност", verification: "KSeF проверка", ksefNumber: "KSeF номер", verificationLink: "Линк за проверка", footer: "Долен колонтитул", registry: "Регистрационни данни", translatedRepresentation: "Този документ е преведено, четимо представяне на полска структурирана фактура KSeF.", originalPolish: "Полски оригинал", translated: "Превод"
  },
  hr: {
    invoice: "Račun", invoiceType: "Vrsta računa", invoiceNumber: "Broj računa", issueDate: "Datum izdavanja", saleDate: "Datum prodaje", currency: "Valuta", seller: "Prodavatelj", buyer: "Kupac", vatId: "PDV ID", address: "Adresa", description: "Opis", quantity: "Količina", unit: "Jedinica", unitPrice: "Jedinična cijena", vatRate: "Stopa PDV-a", netValue: "Neto vrijednost", grossValue: "Bruto vrijednost", netTotal: "Neto ukupno", vatTotal: "PDV ukupno", grossTotal: "Bruto ukupno", payment: "Plaćanje", paymentTerms: "Uvjeti plaćanja", partialPayments: "Djelomična plaćanja", paid: "Plaćeno", paidDate: "Datum plaćanja", amount: "Iznos", taxSummary: "Sažetak PDV-a", bankAccounts: "Bankovni računi", bankName: "Naziv banke", accountNumber: "Broj računa", accountDescription: "Opis računa", dueDate: "Datum dospijeća", method: "Metoda", notes: "Napomene", additionalInformation: "Dodatne informacije", thirdParties: "Dodatne strane", authorizedParty: "Ovlaštena strana", settlements: "Obračuni", charges: "Naknade", deductions: "Odbici", reason: "Razlog", orders: "Narudžbe", orderNumber: "Broj narudžbe", contractNumber: "Broj ugovora", totalValue: "Ukupna vrijednost", verification: "KSeF provjera", footer: "Podnožje", registry: "Registracijski podaci", translatedRepresentation: "Ovaj dokument je prevedeni, čitljivi prikaz poljskog strukturiranog KSeF računa.", originalPolish: "Poljski izvornik", translated: "Prijevod"
  },
  sl: {
    invoice: "Račun", invoiceType: "Vrsta računa", invoiceNumber: "Številka računa", issueDate: "Datum izdaje", saleDate: "Datum prodaje", currency: "Valuta", seller: "Prodajalec", buyer: "Kupec", vatId: "ID za DDV", address: "Naslov", description: "Opis", quantity: "Količina", unit: "Enota", unitPrice: "Cena na enoto", vatRate: "Stopnja DDV", netValue: "Neto vrednost", grossValue: "Bruto vrednost", netTotal: "Neto skupaj", vatTotal: "DDV skupaj", grossTotal: "Bruto skupaj", payment: "Plačilo", paymentTerms: "Plačilni pogoji", partialPayments: "Delna plačila", paid: "Plačano", paidDate: "Datum plačila", amount: "Znesek", taxSummary: "Povzetek DDV", bankAccounts: "Bančni računi", bankName: "Ime banke", accountNumber: "Številka računa", accountDescription: "Opis računa", dueDate: "Datum zapadlosti", method: "Metoda", notes: "Opombe", additionalInformation: "Dodatne informacije", thirdParties: "Dodatne stranke", authorizedParty: "Pooblaščena stranka", settlements: "Poravnave", charges: "Dajatve", deductions: "Odbitki", reason: "Razlog", orders: "Naročila", orderNumber: "Številka naročila", contractNumber: "Številka pogodbe", totalValue: "Skupna vrednost", verification: "Preverjanje KSeF", footer: "Noga", registry: "Registracijski podatki", translatedRepresentation: "Ta dokument je preveden, berljiv prikaz poljskega strukturiranega računa KSeF.", originalPolish: "Poljski izvirnik", translated: "Prevod"
  },
  lt: {
    invoice: "Sąskaita faktūra", invoiceType: "Sąskaitos tipas", invoiceNumber: "Sąskaitos numeris", issueDate: "Išrašymo data", saleDate: "Pardavimo data", currency: "Valiuta", seller: "Pardavėjas", buyer: "Pirkėjas", vatId: "PVM mokėtojo kodas", address: "Adresas", description: "Aprašymas", quantity: "Kiekis", unit: "Vienetas", unitPrice: "Vieneto kaina", vatRate: "PVM tarifas", netValue: "Grynoji vertė", grossValue: "Bendroji vertė", netTotal: "Grynoji suma", vatTotal: "PVM suma", grossTotal: "Bendroji suma", payment: "Mokėjimas", paymentTerms: "Mokėjimo sąlygos", partialPayments: "Daliniai mokėjimai", paid: "Apmokėta", paidDate: "Mokėjimo data", amount: "Suma", taxSummary: "PVM suvestinė", bankAccounts: "Banko sąskaitos", bankName: "Banko pavadinimas", accountNumber: "Sąskaitos numeris", accountDescription: "Sąskaitos aprašymas", dueDate: "Terminas", method: "Metodas", notes: "Pastabos", additionalInformation: "Papildoma informacija", thirdParties: "Papildomos šalys", authorizedParty: "Įgaliota šalis", settlements: "Atsiskaitymai", charges: "Mokesčiai", deductions: "Atskaitymai", reason: "Priežastis", orders: "Užsakymai", orderNumber: "Užsakymo numeris", contractNumber: "Sutarties numeris", totalValue: "Bendra vertė", verification: "KSeF patikra", footer: "Poraštė", registry: "Registracijos duomenys", translatedRepresentation: "Šis dokumentas yra išverstas, žmogui skaitomas Lenkijos struktūrinės KSeF sąskaitos atvaizdas.", originalPolish: "Lenkiškas originalas", translated: "Vertimas"
  },
  lv: {
    invoice: "Rēķins", invoiceType: "Rēķina veids", invoiceNumber: "Rēķina numurs", issueDate: "Izdošanas datums", saleDate: "Pārdošanas datums", currency: "Valūta", seller: "Pārdevējs", buyer: "Pircējs", vatId: "PVN numurs", address: "Adrese", description: "Apraksts", quantity: "Daudzums", unit: "Vienība", unitPrice: "Vienības cena", vatRate: "PVN likme", netValue: "Neto vērtība", grossValue: "Bruto vērtība", netTotal: "Neto kopā", vatTotal: "PVN kopā", grossTotal: "Bruto kopā", payment: "Maksājums", paymentTerms: "Maksājuma noteikumi", partialPayments: "Daļēji maksājumi", paid: "Samaksāts", paidDate: "Maksājuma datums", amount: "Summa", taxSummary: "PVN kopsavilkums", bankAccounts: "Bankas konti", bankName: "Bankas nosaukums", accountNumber: "Konta numurs", accountDescription: "Konta apraksts", dueDate: "Termiņš", method: "Metode", notes: "Piezīmes", additionalInformation: "Papildu informācija", thirdParties: "Papildu puses", authorizedParty: "Pilnvarotā puse", settlements: "Norēķini", charges: "Piemaksas", deductions: "Atskaitījumi", reason: "Iemesls", orders: "Pasūtījumi", orderNumber: "Pasūtījuma numurs", contractNumber: "Līguma numurs", totalValue: "Kopējā vērtība", verification: "KSeF pārbaude", footer: "Kājene", registry: "Reģistrācijas dati", translatedRepresentation: "Šis dokuments ir tulkots, cilvēkam lasāms Polijas strukturētā KSeF rēķina attēlojums.", originalPolish: "Poļu oriģināls", translated: "Tulkojums"
  },
  et: {
    invoice: "Arve", invoiceType: "Arve tüüp", invoiceNumber: "Arve number", issueDate: "Väljastamise kuupäev", saleDate: "Müügi kuupäev", currency: "Valuuta", seller: "Müüja", buyer: "Ostja", vatId: "KMKR number", address: "Aadress", description: "Kirjeldus", quantity: "Kogus", unit: "Ühik", unitPrice: "Ühiku hind", vatRate: "Käibemaksumäär", netValue: "Netoväärtus", grossValue: "Brutoväärtus", netTotal: "Netosumma", vatTotal: "Käibemaks kokku", grossTotal: "Brutosumma", payment: "Makse", paymentTerms: "Maksetingimused", partialPayments: "Osamaksed", paid: "Makstud", paidDate: "Makse kuupäev", amount: "Summa", taxSummary: "KM kokkuvõte", bankAccounts: "Pangakontod", bankName: "Panga nimi", accountNumber: "Konto number", accountDescription: "Konto kirjeldus", dueDate: "Tähtaeg", method: "Meetod", notes: "Märkused", additionalInformation: "Lisateave", thirdParties: "Lisapooled", authorizedParty: "Volitatud pool", settlements: "Arveldused", charges: "Tasud", deductions: "Mahaarvamised", reason: "Põhjus", orders: "Tellimused", orderNumber: "Tellimuse number", contractNumber: "Lepingu number", totalValue: "Koguväärtus", verification: "KSeF kontroll", footer: "Jalus", registry: "Registriandmed", translatedRepresentation: "See dokument on Poola KSeF struktureeritud arve tõlgitud ja loetav esitus.", originalPolish: "Poolakeelne originaal", translated: "Tõlge"
  },
  da: {
    invoice: "Faktura", invoiceType: "Fakturatype", invoiceNumber: "Fakturanummer", issueDate: "Udstedelsesdato", saleDate: "Salgsdato", currency: "Valuta", seller: "Sælger", buyer: "Køber", vatId: "Momsnummer", address: "Adresse", description: "Beskrivelse", quantity: "Antal", unit: "Enhed", unitPrice: "Enhedspris", vatRate: "Momssats", netValue: "Nettoværdi", grossValue: "Bruttoværdi", netTotal: "Netto i alt", vatTotal: "Moms i alt", grossTotal: "Brutto i alt", payment: "Betaling", paymentTerms: "Betalingsbetingelser", partialPayments: "Delbetalinger", paid: "Betalt", paidDate: "Betalingsdato", amount: "Beløb", taxSummary: "Momsoversigt", bankAccounts: "Bankkonti", bankName: "Banknavn", accountNumber: "Kontonummer", accountDescription: "Kontobeskrivelse", dueDate: "Forfaldsdato", method: "Metode", notes: "Noter", additionalInformation: "Yderligere oplysninger", thirdParties: "Yderligere parter", authorizedParty: "Autoriseret part", settlements: "Afregninger", charges: "Gebyrer", deductions: "Fradrag", reason: "Årsag", orders: "Ordrer", orderNumber: "Ordrenummer", contractNumber: "Kontraktnummer", totalValue: "Samlet værdi", verification: "KSeF-verifikation", footer: "Sidefod", registry: "Registreringsoplysninger", translatedRepresentation: "Dette dokument er en oversat, læsbar gengivelse af en polsk struktureret KSeF-faktura.", originalPolish: "Polsk original", translated: "Oversættelse"
  },
  sv: {
    invoice: "Faktura", invoiceType: "Fakturatyp", invoiceNumber: "Fakturanummer", issueDate: "Utfärdandedatum", saleDate: "Försäljningsdatum", currency: "Valuta", seller: "Säljare", buyer: "Köpare", vatId: "Momsregistreringsnummer", address: "Adress", description: "Beskrivning", quantity: "Antal", unit: "Enhet", unitPrice: "Enhetspris", vatRate: "Momssats", netValue: "Nettovärde", grossValue: "Bruttovärde", netTotal: "Netto totalt", vatTotal: "Moms totalt", grossTotal: "Brutto totalt", payment: "Betalning", paymentTerms: "Betalningsvillkor", partialPayments: "Delbetalningar", paid: "Betald", paidDate: "Betalningsdatum", amount: "Belopp", taxSummary: "Momsöversikt", bankAccounts: "Bankkonton", bankName: "Banknamn", accountNumber: "Kontonummer", accountDescription: "Kontobeskrivning", dueDate: "Förfallodatum", method: "Metod", notes: "Anteckningar", additionalInformation: "Ytterligare information", thirdParties: "Ytterligare parter", authorizedParty: "Auktoriserad part", settlements: "Avräkningar", charges: "Avgifter", deductions: "Avdrag", reason: "Orsak", orders: "Order", orderNumber: "Ordernummer", contractNumber: "Kontraktsnummer", totalValue: "Totalt värde", verification: "KSeF-verifiering", footer: "Sidfot", registry: "Registreringsuppgifter", translatedRepresentation: "Detta dokument är en översatt, läsbar representation av en polsk strukturerad KSeF-faktura.", originalPolish: "Polskt original", translated: "Översättning"
  },
  fi: {
    invoice: "Lasku", invoiceType: "Laskutyyppi", invoiceNumber: "Laskun numero", issueDate: "Laskun päiväys", saleDate: "Myyntipäivä", currency: "Valuutta", seller: "Myyjä", buyer: "Ostaja", vatId: "ALV-tunnus", address: "Osoite", description: "Kuvaus", quantity: "Määrä", unit: "Yksikkö", unitPrice: "Yksikköhinta", vatRate: "ALV-kanta", netValue: "Nettoarvo", grossValue: "Bruttoarvo", netTotal: "Netto yhteensä", vatTotal: "ALV yhteensä", grossTotal: "Brutto yhteensä", payment: "Maksu", paymentTerms: "Maksuehdot", partialPayments: "Osamaksut", paid: "Maksettu", paidDate: "Maksupäivä", amount: "Summa", taxSummary: "ALV-yhteenveto", bankAccounts: "Pankkitilit", bankName: "Pankin nimi", accountNumber: "Tilinumero", accountDescription: "Tilin kuvaus", dueDate: "Eräpäivä", method: "Tapa", notes: "Huomautukset", additionalInformation: "Lisätiedot", thirdParties: "Lisäosapuolet", authorizedParty: "Valtuutettu osapuoli", settlements: "Tilitykset", charges: "Maksut", deductions: "Vähennykset", reason: "Syy", orders: "Tilaukset", orderNumber: "Tilausnumero", contractNumber: "Sopimusnumero", totalValue: "Kokonaisarvo", verification: "KSeF-varmennus", footer: "Alatunniste", registry: "Rekisteritiedot", translatedRepresentation: "Tämä asiakirja on käännetty, ihmisen luettava esitys puolalaisesta KSeF-rakenteisesta laskusta.", originalPolish: "Puolankielinen alkuperäinen", translated: "Käännös"
  },
  no: {
    invoice: "Faktura", invoiceType: "Fakturatype", invoiceNumber: "Fakturanummer", issueDate: "Utstedelsesdato", saleDate: "Salgsdato", currency: "Valuta", seller: "Selger", buyer: "Kjøper", vatId: "MVA-nummer", address: "Adresse", description: "Beskrivelse", quantity: "Antall", unit: "Enhet", unitPrice: "Enhetspris", vatRate: "MVA-sats", netValue: "Nettoverdi", grossValue: "Bruttoverdi", netTotal: "Netto totalt", vatTotal: "MVA totalt", grossTotal: "Brutto totalt", payment: "Betaling", paymentTerms: "Betalingsvilkår", partialPayments: "Delbetalinger", paid: "Betalt", paidDate: "Betalingsdato", amount: "Beløp", taxSummary: "MVA-oversikt", bankAccounts: "Bankkontoer", bankName: "Banknavn", accountNumber: "Kontonummer", accountDescription: "Kontobeskrivelse", dueDate: "Forfallsdato", method: "Metode", notes: "Notater", additionalInformation: "Tilleggsinformasjon", thirdParties: "Tilleggsparter", authorizedParty: "Autorisert part", settlements: "Oppgjør", charges: "Gebyrer", deductions: "Fradrag", reason: "Årsak", orders: "Ordre", orderNumber: "Ordrenummer", contractNumber: "Kontraktsnummer", totalValue: "Total verdi", verification: "KSeF-verifisering", footer: "Bunntekst", registry: "Registreringsopplysninger", translatedRepresentation: "Dette dokumentet er en oversatt, lesbar fremstilling av en polsk strukturert KSeF-faktura.", originalPolish: "Polsk original", translated: "Oversettelse"
  },
  el: {
    invoice: "Τιμολόγιο", invoiceType: "Τύπος τιμολογίου", invoiceNumber: "Αριθμός τιμολογίου", issueDate: "Ημερομηνία έκδοσης", saleDate: "Ημερομηνία πώλησης", currency: "Νόμισμα", seller: "Πωλητής", buyer: "Αγοραστής", vatId: "ΑΦΜ / ΦΠΑ", address: "Διεύθυνση", description: "Περιγραφή", quantity: "Ποσότητα", unit: "Μονάδα", unitPrice: "Τιμή μονάδας", vatRate: "Συντελεστής ΦΠΑ", netValue: "Καθαρή αξία", grossValue: "Μικτή αξία", netTotal: "Καθαρό σύνολο", vatTotal: "Σύνολο ΦΠΑ", grossTotal: "Μικτό σύνολο", payment: "Πληρωμή", paymentTerms: "Όροι πληρωμής", partialPayments: "Μερικές πληρωμές", paid: "Πληρώθηκε", paidDate: "Ημερομηνία πληρωμής", amount: "Ποσό", taxSummary: "Σύνοψη ΦΠΑ", bankAccounts: "Τραπεζικοί λογαριασμοί", bankName: "Όνομα τράπεζας", accountNumber: "Αριθμός λογαριασμού", accountDescription: "Περιγραφή λογαριασμού", dueDate: "Ημερομηνία λήξης", method: "Μέθοδος", notes: "Σημειώσεις", additionalInformation: "Πρόσθετες πληροφορίες", thirdParties: "Πρόσθετα μέρη", authorizedParty: "Εξουσιοδοτημένο μέρος", settlements: "Διακανονισμοί", charges: "Χρεώσεις", deductions: "Εκπτώσεις", reason: "Αιτιολογία", orders: "Παραγγελίες", orderNumber: "Αριθμός παραγγελίας", contractNumber: "Αριθμός σύμβασης", totalValue: "Συνολική αξία", verification: "Επαλήθευση KSeF", footer: "Υποσέλιδο", registry: "Στοιχεία μητρώου", translatedRepresentation: "Το έγγραφο αυτό είναι μια μεταφρασμένη, αναγνώσιμη αναπαράσταση ενός πολωνικού δομημένου τιμολογίου KSeF.", originalPolish: "Πολωνικό πρωτότυπο", translated: "Μετάφραση"
  }
};
