import type { getLabels } from "@/lib/translation/dictionaries";
import { PAYMENT_METHOD_LABELS, PAYMENT_METHOD_OFFICIAL_KEYS } from "@/lib/translation/payment-methods";
import type { LanguageCode } from "@/types/invoice";
import bgGenerated from "@/lib/mf-fa3/official-labels/generated/bg.json";
import csGenerated from "@/lib/mf-fa3/official-labels/generated/cs.json";
import daGenerated from "@/lib/mf-fa3/official-labels/generated/da.json";
import deGenerated from "@/lib/mf-fa3/official-labels/generated/de.json";
import elGenerated from "@/lib/mf-fa3/official-labels/generated/el.json";
import enGenerated from "@/lib/mf-fa3/official-labels/generated/en.json";
import esGenerated from "@/lib/mf-fa3/official-labels/generated/es.json";
import etGenerated from "@/lib/mf-fa3/official-labels/generated/et.json";
import fiGenerated from "@/lib/mf-fa3/official-labels/generated/fi.json";
import frGenerated from "@/lib/mf-fa3/official-labels/generated/fr.json";
import hrGenerated from "@/lib/mf-fa3/official-labels/generated/hr.json";
import huGenerated from "@/lib/mf-fa3/official-labels/generated/hu.json";
import itGenerated from "@/lib/mf-fa3/official-labels/generated/it.json";
import ltGenerated from "@/lib/mf-fa3/official-labels/generated/lt.json";
import lvGenerated from "@/lib/mf-fa3/official-labels/generated/lv.json";
import nlGenerated from "@/lib/mf-fa3/official-labels/generated/nl.json";
import noGenerated from "@/lib/mf-fa3/official-labels/generated/no.json";
import ptGenerated from "@/lib/mf-fa3/official-labels/generated/pt.json";
import roGenerated from "@/lib/mf-fa3/official-labels/generated/ro.json";
import skGenerated from "@/lib/mf-fa3/official-labels/generated/sk.json";
import slGenerated from "@/lib/mf-fa3/official-labels/generated/sl.json";
import svGenerated from "@/lib/mf-fa3/official-labels/generated/sv.json";

type AppLabelKey = keyof ReturnType<typeof getLabels>;

export const OFFICIAL_LABEL_MAP: Record<string, AppLabelKey> = {
  "invoice.header.invoiceNumberLabel": "invoiceNumber",
  "invoice.header.ksefNumberLabel": "ksefNumber",
  "invoice.header.vat": "invoiceTypeBasic",
  "invoice.header.advance": "invoiceTypeAdvance",
  "invoice.header.settlement": "invoiceTypeFinal",
  "invoice.header.correction": "invoiceTypeCorrection",
  "invoice.header.correctionCollective": "discountCorrection",
  "invoice.subject1.seller": "seller",
  "invoice.subject1.name": "seller",
  "invoice.subject1.address": "address",
  "invoice.subject1.nip": "vatId",
  "invoice.subject2.buyer": "buyer",
  "invoice.subject2.name": "buyer",
  "invoice.subject2.address": "address",
  "invoice.subject2.nip": "vatId",
  "invoice.subject3.otherEntity": "thirdParties",
  "invoice.authorizedSubject.authorizedSubject": "authorizedParty",
  "invoice.details.header": "details",
  "invoice.details.issueDate": "issueDateWithKsefClause",
  "invoice.details.issuePlace": "issuePlace",
  "invoice.details.discountPeriod": "discountPeriod",
  "invoice.details.deliveryOrServiceDate": "deliveryOrServiceDate",
  "invoice.details.deliveryOrServiceDateFrom": "servicePeriodFrom",
  "invoice.details.deliveryOrServiceDateTo": "servicePeriodTo",
  "invoice.details.getMoneyDate": "paymentReceivedDate",
  "invoice.details.currencyCode": "currencyCode",
  "invoice.details.commonCurrencyRate": "commonCurrencyRate",
  "invoice.details.currencyRate": "currencyRate",
  "invoice.details.ossProcedure": "ossProcedure",
  "invoice.details.advanceInvoiceNumbers": "advanceInvoices",
  "invoice.correctedInvoice.sectionHeader": "correctedInvoiceData",
  "invoice.correctedInvoice.invoiceNumber": "correctedInvoiceNumber",
  "invoice.correctedInvoice.correctionReason": "reason",
  "invoice.correctedInvoice.correctionEffectType": "correctionType",
  "invoice.rows.header": "rows",
  "invoice.rows.lp": "line",
  "invoice.rows.productName": "description",
  "invoice.rows.quantity": "quantity",
  "invoice.rows.unit": "unit",
  "invoice.rows.netUnitPrice": "unitPrice",
  "invoice.rows.grossUnitPrice": "grossValue",
  "invoice.rows.taxRate": "vatRate",
  "invoice.rows.netSalesValue": "netValue",
  "invoice.rows.grossSalesValue": "grossValue",
  "invoice.rows.vatSalesValue": "vatTotal",
  "invoice.rows.currencyRate": "currencyRate",
  "invoice.rows.index": "index",
  "invoice.rows.uniqueRowNumber": "uniqueRowNumber",
  "invoice.rows.discount": "discount",
  "invoice.rows.gtin": "gtin",
  "invoice.rows.pkwiu": "pkwiu",
  "invoice.rows.cn": "cn",
  "invoice.rows.pkob": "pkob",
  "invoice.rows.gtu": "gtu",
  "invoice.rows.procedure": "procedure",
  "invoice.rows.totalAmountDue": "grossTotal",
  "invoice.discount.header": "discountCorrection",
  "invoice.discount.lp": "line",
  "invoice.discount.productName": "description",
  "invoice.discount.quantity": "quantity",
  "invoice.discount.unit": "unit",
  "invoice.discount.totalValue": "totalValue",
  "invoice.order.productName": "description",
  "invoice.order.quantity": "quantity",
  "invoice.order.unit": "unit",
  "invoice.order.netUnitPrice": "unitPrice",
  "invoice.order.taxRate": "vatRate",
  "invoice.order.netSalesValue": "netValue",
  "invoice.order.taxAmount": "vatTotal",
  "invoice.order.currencyRate": "currencyRate",
  "invoice.order.orderNumber": "orderNumber",
  "invoice.order.totalAmountDue": "grossTotal",
  "invoice.summary.sectionHeader": "taxSummary",
  "invoice.summary.lp": "line",
  "invoice.summary.taxRate": "taxRate",
  "invoice.summary.netAmount": "netValue",
  "invoice.summary.taxAmount": "vatTotal",
  "invoice.summary.grossAmount": "grossValue",
  "invoice.summary.taxAmountPLN": "vatTotal",
  "invoice.annotations.header": "annotations",
  "invoice.annotations.partialPayMechanism": "splitPayment",
  "invoice.annotations.cashMethod": "cashAccounting",
  "invoice.annotations.reverseTax": "reverseCharge",
  "invoice.annotations.selfInvoice": "selfBilling",
  "invoice.annotations.threePartsSimplerMethod": "simplifiedTriangularProcedure",
  "invoice.annotations.marginProcedure": "marginProcedure",
  "invoice.annotations.noTaxBase": "taxExemption",
  "invoice.additionalInformation.additionalInformationLabel": "additionalInformation",
  "invoice.additionalInformation.additionalDescription": "additionalInformation",
  "invoice.additionalInformation.ordinalNumber": "line",
  "invoice.additionalInformation.rowNumber": "line",
  "invoice.additionalInformation.infoType": "key",
  "invoice.additionalInformation.infoContent": "value",
  "invoice.information.header": "additionalInformation",
  "invoice.information.invoiceFooter": "footer",
  "invoice.settlement.header": "settlements",
  "invoice.settlement.charges": "charges",
  "invoice.settlement.deductions": "deductions",
  "invoice.settlement.chargeReason": "reason",
  "invoice.settlement.deductionReason": "reason",
  "invoice.settlement.totalCharges": "totalCharges",
  "invoice.settlement.totalDeductions": "totalDeductions",
  "invoice.settlement.toPay": "amountToPay",
  "invoice.settlement.toSettle": "amountToSettle",
  "invoice.payment.payment": "payment",
  "invoice.payment.paymentInformation": "paymentInformation",
  "invoice.payment.maturityDate": "dueDate",
  "invoice.payment.paymentMethod": "method",
  "invoice.payment.paymentDate": "paidDate",
  "invoice.payment.bankAccountNumber": "accountNumber",
  "invoice.payment.factorsBankAccountNumber": "factorBankAccounts",
  "invoice.payment.conditionalDiscount": "conditionalDiscount",
  "invoice.payment.discountConditions": "discountConditions",
  "invoice.payment.discountAmount": "discountAmount",
  "invoice.registers.header": "registry",
  "invoice.registers.fullAccountNumber": "accountNumber",
  "invoice.registers.fullNrbAccountNumber": "accountNumber",
  "invoice.registers.fullForeignAccountNumber": "accountNumber",
  "invoice.registers.swiftCode": "swift",
  "invoice.registers.ownBankAccount": "bankAccount",
  "invoice.registers.bankName": "bankName",
  "invoice.registers.accountDescription": "accountDescription",
  "invoice.registers.fullName": "seller",
  "invoice.registers.polish": "bankAccount",
  "invoice.registers.foreign": "bankAccount",
  "invoice.transaction.header": "transactionTerms",
  "invoice.transaction.contract": "contracts",
  "invoice.transaction.contractDate": "contractDate",
  "invoice.transaction.contractNumber": "contractNumber",
  "invoice.transaction.order": "orders",
  "invoice.transaction.orderDate": "orderDate",
  "invoice.transaction.orderNumber": "orderNumber",
  "invoice.transaction.currency": "contractualCurrency",
  "invoice.transaction.rate": "contractualRate",
  "invoice.transaction.batchNumber": "batchNumbers",
  "invoice.transaction.deliveryTerms": "deliveryTerms",
  "invoice.transport.header": "transportType",
  "invoice.transport.type": "transportType",
  "invoice.transport.otherTypeDescription": "otherTypeDescription",
  "invoice.transport.cargoDescription": "cargoDescription",
  "invoice.transport.otherCargoDescription": "otherCargoDescription",
  "invoice.transport.packageUnit": "packageUnit",
  "invoice.transport.startDateTime": "transportStart",
  "invoice.transport.endDateTime": "transportEnd",
  "invoice.transport.shipFrom": "shipFrom",
  "invoice.transport.shipTo": "shipTo",
  "invoice.transport.intermediateAddress": "shipThrough",
  "invoice.carrier.carrier": "carrier",
  "invoice.additionalInformation.documentDate": "issueDate",
  "invoice.additionalInformation.documentNumber": "documentNumber",
  "invoice.additionalInformation.exciseTaxRefund": "exciseTaxRefund",
  "invoice.additionalInformation.fpLabel": "additionalInformation",
  "invoice.additionalInformation.informationContent": "value",
  "invoice.additionalInformation.ksefDocumentNumber": "ksefNumber",
  "invoice.additionalInformation.paymentDocuments": "payment",
  "invoice.additionalInformation.tpLabel": "relatedParty",
  "invoice.additionalInformation.typeOfInformation": "key",
  "invoice.address.apartmentNumber": "address",
  "invoice.address.communeName": "address",
  "invoice.address.countryName": "address",
  "invoice.address.districtName": "address",
  "invoice.address.GLN": "address",
  "invoice.address.houseNumber": "address",
  "invoice.address.postName": "address",
  "invoice.address.streetName": "address",
  "invoice.address.townName": "address",
  "invoice.address.voivodeshipName": "address",
  "invoice.address.zipCode": "address",
  "invoice.annotations.bodyNumber": "documentNumber",
  "invoice.annotations.airDelivery": "newTransportMeans",
  "invoice.annotations.antiques": "marginProcedure",
  "invoice.annotations.artPieces": "marginProcedure",
  "invoice.annotations.boatDelivery": "newTransportMeans",
  "invoice.annotations.chassisNumber": "documentNumber",
  "invoice.annotations.description": "description",
  "invoice.annotations.directiveLaw": "directiveBasis",
  "invoice.annotations.factoryNumber": "documentNumber",
  "invoice.annotations.frameNumber": "documentNumber",
  "invoice.annotations.hullNumber": "documentNumber",
  "invoice.annotations.landDelivery": "newTransportMeans",
  "invoice.annotations.law": "legalBasis",
  "invoice.annotations.newTransportsDelivery": "newTransportMeans",
  "invoice.annotations.newTransportType": "transportType",
  "invoice.annotations.noTaxBaseDocument": "legalBasis",
  "invoice.annotations.noTaxBaseDocument2": "directiveBasis",
  "invoice.annotations.noTaxBaseDocument3": "otherBasis",
  "invoice.annotations.otherLaw": "otherBasis",
  "invoice.annotations.transportApprovalDate": "issueDate",
  "invoice.annotations.transportBrand": "description",
  "invoice.annotations.transportColor": "description",
  "invoice.annotations.transportMileage": "quantity",
  "invoice.annotations.transportModel": "description",
  "invoice.annotations.transportProductionYear": "issueDate",
  "invoice.annotations.transportRegistrationNumber": "documentNumber",
  "invoice.annotations.transportType": "transportType",
  "invoice.annotations.travelAgencies": "marginProcedure",
  "invoice.annotations.usedGoods": "marginProcedure",
  "invoice.annotations.usePermissionDate": "issueDate",
  "invoice.annotations.vin": "documentNumber",
  "invoice.attachment.blockHeader": "attachments",
  "invoice.attachment.details": "details",
  "invoice.attachment.tableLabel": "attachments",
  "invoice.attachment.tableSummary": "taxSummary",
  "invoice.authorizedSubject.address": "address",
  "invoice.authorizedSubject.contactData": "additionalInformation",
  "invoice.authorizedSubject.correspondenceAddress": "address",
  "invoice.authorizedSubject.correspondenceAddress2": "address",
  "invoice.authorizedSubject.email": "additionalInformation",
  "invoice.authorizedSubject.eori": "vatId",
  "invoice.authorizedSubject.noTaxId": "vatId",
  "invoice.authorizedSubject.otherTaxId": "vatId",
  "invoice.authorizedSubject.phone": "additionalInformation",
  "invoice.authorizedSubject.role": "authorizedParty",
  "invoice.carrier.carrierAddress": "address",
  "invoice.correctedInvoice.correctInvoiceNumber": "correctedInvoiceNumber",
  "invoice.correctedInvoice.identificationHeader": "correctedInvoiceData",
  "invoice.correctedInvoice.identificationHeaderIndexed": "correctedInvoiceData",
  "invoice.correctedInvoice.issueDate": "issueDate",
  "invoice.correctedInvoice.ksefNumber": "ksefNumber",
  "invoice.details.assignKsefNumberDate": "issueDate",
  "invoice.details.costAmount": "amount",
  "invoice.details.currencyRate2": "currencyRate",
  "invoice.details.getDate": "issueDate",
  "invoice.details.getMoneyDate2": "paymentReceivedDate",
  "invoice.details.invoiceDate": "issueDate",
  "invoice.details.invoiceDateSentToKsef": "issueDate",
  "invoice.details.invoiceDateShort": "issueDate",
  "invoice.details.invoiceNumber": "invoiceNumber",
  "invoice.details.paymentReceivedDate": "paymentReceivedDate",
  "invoice.details.place": "issuePlace",
  "invoice.details.to": "servicePeriodTo",
  "invoice.footer.margin": "marginProcedure",
  "invoice.header.attachmentWarning": "attachments",
  "invoice.header.ksefPart1": "verification",
  "invoice.header.ksefPart2": "verification",
  "invoice.header.ksefPart3": "verification",
  "invoice.footer.generatedIn": "generatedAt",
  "invoice.header.correctedInvoiceVatRr": "invoiceTypeCorrection",
  "invoice.header.correctionAdvance": "invoiceTypeCorrection",
  "invoice.header.correctionSettlement": "invoiceTypeCorrection",
  "invoice.header.primalInvoiceVatRr": "invoiceTypeBasic",
  "invoice.header.simplified": "invoiceTypeBasic",
  "invoice.order.additionalInfo": "additionalInformation",
  "invoice.order.advancePaymentAmount": "amount",
  "invoice.order.advancePaymentAmountCorrection": "amount",
  "invoice.order.cn": "cn",
  "invoice.order.exciseTaxAmount": "amount",
  "invoice.order.gtin": "gtin",
  "invoice.order.gtu": "gtu",
  "invoice.order.index": "index",
  "invoice.order.issuedInCurrency": "currency",
  "invoice.order.lp": "line",
  "invoice.order.orderValueWithTax": "grossValue",
  "invoice.order.ossTaxRate": "taxRate",
  "invoice.order.pkob": "pkob",
  "invoice.order.pkwiu": "pkwiu",
  "invoice.order.procedure": "procedure",
  "invoice.order.procedureMarkings": "procedure",
  "invoice.order.productMarker": "productMarker",
  "invoice.order.receivedAdvance": "amount",
  "invoice.order.stateBefore": "stateBefore",
  "invoice.order.uniqueRowNumber": "uniqueRowNumber",
  "invoice.payment.description": "description",
  "invoice.payment.farmer": "bankAccount",
  "invoice.payment.getter": "buyer",
  "invoice.payment.ksefTransferId": "ksefNumber",
  "invoice.payment.moneylessLink": "paymentLink",
  "invoice.payment.noPayment": "noPayment",
  "invoice.payment.other": "method",
  "invoice.payment.otherPaymentDescription": "description",
  "invoice.payment.paidAllInParts": "paidAllInParts",
  "invoice.payment.paidInPart": "paidInPart",
  "invoice.payment.paidStatus": "paidStatus",
  "invoice.payment.partialPayment": "partialPayments",
  "invoice.payment.partialPaymentAmount": "amount",
  "invoice.payment.partialPaymentDate": "paidDate",
  "invoice.payment.paymentDescription": "description",
  "invoice.payment.paymentDifferent": "method",
  "invoice.payment.paymentInformationContinued": "paymentInformation",
  "invoice.payment.paymentMethod2": "method",
  "invoice.payment.paymentMethod3": "method",
  "invoice.payment.transfer": "method",
  "invoice.qr1.offline": "verification",
  "invoice.qr2.certificate": "verification",
  "invoice.qr2.description": "verificationLink",
  "invoice.qr2.header": "verification",
  "invoice.registers.bdo": "bdo",
  "invoice.registers.billFormat": "registry",
  "invoice.registers.krs": "krs",
  "invoice.registers.regon": "regon",
  "invoice.rows.additionalInfo": "additionalInformation",
  "invoice.rows.amount": "quantity",
  "invoice.rows.deliveryDate": "deliveryOrServiceDate",
  "invoice.rows.costZZP": "amount",
  "invoice.rows.exciseTaxAmount": "amount",
  "invoice.rows.getDate": "issueDate",
  "invoice.rows.getOrMakeDate": "deliveryOrServiceDate",
  "invoice.rows.farmProductCost": "amount",
  "invoice.rows.inWords": "amount",
  "invoice.rows.issuedInCurrency": "currency",
  "invoice.rows.lumpSumTaxRefund": "amount",
  "invoice.rows.name": "description",
  "invoice.rows.ossTaxRate": "taxRate",
  "invoice.rows.procedureMarkings": "procedure",
  "invoice.rows.productMarker": "productMarker",
  "invoice.rows.overallCost": "grossTotal",
  "invoice.rows.priceNoZZP": "netValue",
  "invoice.rows.qualityDesc": "description",
  "invoice.rows.remainingAmount": "amountToPay",
  "invoice.rows.stateBefore": "stateBefore",
  "invoice.rows.unitPrice": "unitPrice",
  "invoice.rows.valueZZP": "grossValue",
  "invoice.rows.wageZZP": "vatRate",
  "invoice.subject1.contactDetails": "additionalInformation",
  "invoice.subject1.contractorNumber": "customerNumber",
  "invoice.subject1.correspondenceAddress": "address",
  "invoice.subject1.eoriNumber": "vatId",
  "invoice.subject1.mailingAddress": "address",
  "invoice.subject1.taxpayerStatus": "vatId",
  "invoice.subject1.vatPrefix": "vatId",
  "invoice.subject1K.address": "address",
  "invoice.subject1K.contactDetails": "additionalInformation",
  "invoice.subject1K.contractorNumber": "customerNumber",
  "invoice.subject1K.correctedContent": "correctedInvoiceData",
  "invoice.subject1K.correctiveContent": "correctedInvoiceData",
  "invoice.subject1K.correspondenceAddress": "address",
  "invoice.subject1K.eoriNumber": "vatId",
  "invoice.subject1K.identificationData": "vatId",
  "invoice.subject1K.mailingAddress": "address",
  "invoice.subject1K.seller": "seller",
  "invoice.subject1K.taxpayerStatus": "vatId",
  "invoice.subject1K.vatPrefix": "vatId",
  "invoice.subject2.contactDetails": "additionalInformation",
  "invoice.subject2.correspondenceAddress": "address",
  "invoice.subject2.customerNumber": "customerNumber",
  "invoice.subject2.eoriNumber": "vatId",
  "invoice.subject2.getterId": "vatId",
  "invoice.subject2.internalId": "vatId",
  "invoice.subject2.mailingAddress": "address",
  "invoice.subject2.noId": "vatId",
  "invoice.subject2.noTaxId": "vatId",
  "invoice.subject2.taxIdOther": "vatId",
  "invoice.subject2.taxPayerStatus": "vatId",
  "invoice.subject2.vatPrefix": "vatId",
  "invoice.subject2.vatUeNumber": "vatId",
  "invoice.subject2k.address": "address",
  "invoice.subject2k.buyer": "buyer",
  "invoice.subject2k.buyerId": "vatId",
  "invoice.subject2k.clientNumber": "customerNumber",
  "invoice.subject2k.contactDetails": "additionalInformation",
  "invoice.subject2k.correctedContent": "correctedInvoiceData",
  "invoice.subject2k.correctiveContent": "correctedInvoiceData",
  "invoice.subject2k.correspondenceAddress": "address",
  "invoice.subject2k.eori": "vatId",
  "invoice.subject2k.identificationData": "vatId",
  "invoice.subject2k.mailingAddress": "address",
  "invoice.subject2k.taxPayerStatus": "vatId",
  "invoice.subject3.address": "address",
  "invoice.subject3.clientNumber": "customerNumber",
  "invoice.subject3.contactData": "additionalInformation",
  "invoice.subject3.correspondenceAddress": "address",
  "invoice.subject3.eori": "vatId",
  "invoice.subject3.getterId": "vatId",
  "invoice.subject3.internalId": "vatId",
  "invoice.subject3.name": "thirdParties",
  "invoice.subject3.nip": "vatId",
  "invoice.subject3.noTaxId": "vatId",
  "invoice.subject3.otherId": "vatId",
  "invoice.subject3.otherRole": "thirdParties",
  "invoice.subject3.otherTaxId": "vatId",
  "invoice.subject3.role": "thirdParties",
  "invoice.subject3.roleDescription": "description",
  "invoice.subject3.share": "amount",
  "invoice.subject3.vatUeNumber": "vatId",
  "invoice.subject3k.address": "address",
  "invoice.subject3k.clientNumber": "customerNumber",
  "invoice.subject3k.correctedContent": "correctedInvoiceData",
  "invoice.subject3k.correctiveContent": "correctedInvoiceData",
  "invoice.subject3k.correspondenceAddress": "address",
  "invoice.subject3k.eori": "vatId",
  "invoice.subject3k.getterId": "vatId",
  "invoice.subject3k.identificationData": "vatId",
  "invoice.subject3k.noTaxId": "vatId",
  "invoice.subject3k.otherEntity": "thirdParties",
  "invoice.subject3k.otherRole": "thirdParties",
  "invoice.subject3k.otherTaxId": "vatId",
  "invoice.subject3k.role": "thirdParties",
  "invoice.subject3k.share": "amount",
  "invoice.subjectContactData.e-mail": "additionalInformation",
  "invoice.subjectContactData.email": "additionalInformation",
  "invoice.subjectContactData.phone": "additionalInformation",
  "invoice.subjectIdentificationData.fullName": "seller",
  "invoice.subjectIdentificationData.internalId": "vatId",
  "invoice.subjectIdentificationData.name": "seller",
  "invoice.subjectIdentificationData.nameSurname": "seller",
  "invoice.subjectIdentificationData.nip": "vatId",
  "invoice.subjectIdentificationData.noId": "vatId",
  "invoice.subjectIdentificationData.tradeName": "seller",
  "invoice.summary.5": "taxRate",
  "invoice.summary.0domestic": "taxRate",
  "invoice.summary.0export": "taxRate",
  "invoice.summary.0long": "taxRate",
  "invoice.summary.0mid": "taxRate",
  "invoice.summary.0short": "taxRate",
  "invoice.summary.0wdt": "taxRate",
  "invoice.summary.23or22": "taxRate",
  "invoice.summary.4or3": "taxRate",
  "invoice.summary.8or7": "taxRate",
  "invoice.summary.margin": "marginProcedure",
  "invoice.summary.noTax": "taxExemption",
  "invoice.summary.npBasedArt100": "taxExemption",
  "invoice.summary.npExcludingArt100": "taxExemption",
  "invoice.summary.oss": "ossProcedure",
  "invoice.summary.reverseTax": "reverseCharge",
  "invoice.summary.taxFree": "taxExemption",
  "invoice.transaction.currencyAndRate": "contractualRate",
  "invoice.transport.dataHeader": "transportType",
  "invoice.transport.gln": "address",
  "invoice.transport.orderNumber": "orderNumber",
  "invoice.transport.otherCargo": "otherCargoDescription",
  "invoice.transport.otherType": "otherTypeDescription",
  "invoice.transport.shipmentHeader": "transportType",
  "invoice.upo.authorizationDocumentShortcut": "verification",
  "invoice.upo.complexId": "verification",
  "invoice.upo.contextAuthorizationId": "verification",
  "invoice.upo.contextType": "verification",
  "invoice.upo.documentInfo": "additionalInformation",
  "invoice.upo.documentRangeFrom": "servicePeriodFrom",
  "invoice.upo.documentRangeTo": "servicePeriodTo",
  "invoice.upo.documentsTotal": "quantity",
  "invoice.upo.eDocumentFormCode": "documentNumber",
  "invoice.upo.entityFullName": "seller",
  "invoice.upo.functionValueShortcut": "verification",
  "invoice.upo.internalId": "vatId",
  "invoice.upo.peppolId": "vatId",
  "invoice.upo.registeredInMF": "verification",
  "invoice.upo.sendMethod": "method",
  "invoice.upo.sessionReferenceNumber": "documentNumber",
  "invoice.upo.upoKsef": "verification",
  "invoice.upo.upoPage": "line",
  "invoice.upo.upoPageTotal": "quantity",
  "invoice.upo.vendorNIP": "vatId",
  "invoice.upo.xsdFileLogicName": "fileName",
  "invoice.upo.nip": "vatId",
  "invoice.wz.documentsHeader": "warehouseDocuments",
  "invoice.wz.number": "documentNumber",
  "invoice.attachment.header": "attachments",
  "invoice.attachment.description": "description",
  "invoice.attachment.key": "key",
  "invoice.attachment.value": "value",
  "invoice.qr1.header": "verification",
  "invoice.qr1.description": "verificationLink"
};

const EN = {
  "invoice.subject2.jst": "Invoice concerns a subordinate JST unit: ",
  "invoice.subject2.gv": "Invoice concerns a GV group member: ",
  "invoice.subject2.yes": "YES",
  "invoice.subject2.no": "NO",
  "invoice.annotations.noTaxDelivery": "Supply of goods or services exempt from tax",
  "invoice.annotations.vat22DocumentRequired": "VAT-22 document is required",
  "invoice.annotations.vat22DocumentNotRequired": "VAT-22 document is not required",
  "invoice.discount.all": "Discount applies to all supplies of goods and services made to this buyer in the given period.",
  "invoice.discount.notAll": "Discount does not apply to all supplies of goods and services made to this buyer in the given period.",
  "invoice.transaction.intermediaryDelivery": "Delivery made by an intermediary entity referred to in art. 22 sec. 2d of the VAT Act.",
  "invoice.qr1.header": "Verify that your invoice is in KSeF",
  "invoice.qr1.description": "Cannot scan the code from the image? Use the verification link to verify the invoice.",
  "invoice.registers.fullAccountNumber": "Full account number",
  "invoice.registers.fullNrbAccountNumber": "Full NRB account number",
  "invoice.registers.fullForeignAccountNumber": "Full foreign account number",
  "invoice.registers.swiftCode": "SWIFT code",
  "invoice.registers.ownBankAccount": "Own bank account",
  "invoice.registers.bankName": "Bank name",
  "invoice.registers.accountDescription": "Account description",
  "invoice.registers.header": "Registers"
};

const FR = {
  "invoice.subject2.jst": "La facture concerne une unite subordonnee JST : ",
  "invoice.subject2.gv": "La facture concerne un membre du groupe GV : ",
  "invoice.subject2.yes": "OUI",
  "invoice.subject2.no": "NON",
  "invoice.annotations.noTaxDelivery": "Livraison de biens ou prestation de services exoneree de taxe",
  "invoice.annotations.vat22DocumentRequired": "Le document VAT-22 est requis",
  "invoice.annotations.vat22DocumentNotRequired": "Le document VAT-22 n'est pas requis",
  "invoice.discount.all": "La remise concerne toutes les livraisons de biens et prestations de services effectuees pour cet acheteur pendant la periode indiquee.",
  "invoice.discount.notAll": "La remise ne concerne pas toutes les livraisons de biens et prestations de services effectuees pour cet acheteur pendant la periode indiquee.",
  "invoice.transaction.intermediaryDelivery": "Livraison effectuee par un intermediaire vise a l'art. 22, sec. 2d, de la loi sur la TVA.",
  "invoice.qr1.header": "Verifiez que votre facture se trouve dans KSeF",
  "invoice.qr1.description": "Impossible de scanner le code depuis l'image ? Utilisez le lien de verification pour verifier la facture.",
  "invoice.registers.fullAccountNumber": "Numero de compte complet",
  "invoice.registers.fullNrbAccountNumber": "Numero de compte NRB complet",
  "invoice.registers.fullForeignAccountNumber": "Numero de compte etranger complet",
  "invoice.registers.swiftCode": "Code SWIFT",
  "invoice.registers.ownBankAccount": "Compte bancaire propre",
  "invoice.registers.bankName": "Nom de la banque",
  "invoice.registers.accountDescription": "Description du compte",
  "invoice.registers.header": "Registres"
};

const DE = {
  "invoice.subject2.jst": "Die Rechnung betrifft eine untergeordnete JST-Einheit: ",
  "invoice.subject2.gv": "Die Rechnung betrifft ein Mitglied der GV-Gruppe: ",
  "invoice.subject2.yes": "JA",
  "invoice.subject2.no": "NEIN",
  "invoice.registers.fullAccountNumber": "Vollstandige Kontonummer",
  "invoice.registers.fullNrbAccountNumber": "Vollstandige NRB-Kontonummer",
  "invoice.registers.fullForeignAccountNumber": "Vollstandige auslandische Kontonummer",
  "invoice.registers.swiftCode": "SWIFT-Code",
  "invoice.registers.ownBankAccount": "Eigenes Bankkonto",
  "invoice.registers.bankName": "Bankname",
  "invoice.registers.accountDescription": "Kontobeschreibung",
  "invoice.registers.header": "Register",
  "invoice.discount.all": "Der Rabatt gilt fur alle Warenlieferungen und Dienstleistungen an diesen Kaufer im angegebenen Zeitraum.",
  "invoice.discount.notAll": "Der Rabatt gilt nicht fur alle Warenlieferungen und Dienstleistungen an diesen Kaufer im angegebenen Zeitraum."
};

const ES = {
  "invoice.subject2.jst": "La factura se refiere a una unidad subordinada JST: ",
  "invoice.subject2.gv": "La factura se refiere a un miembro del grupo GV: ",
  "invoice.subject2.yes": "SI",
  "invoice.subject2.no": "NO",
  "invoice.registers.fullAccountNumber": "Numero de cuenta completo",
  "invoice.registers.fullNrbAccountNumber": "Numero de cuenta NRB completo",
  "invoice.registers.fullForeignAccountNumber": "Numero de cuenta extranjera completo",
  "invoice.registers.swiftCode": "Codigo SWIFT",
  "invoice.registers.ownBankAccount": "Cuenta bancaria propia",
  "invoice.registers.bankName": "Nombre del banco",
  "invoice.registers.accountDescription": "Descripcion de la cuenta",
  "invoice.registers.header": "Registros",
  "invoice.discount.all": "El descuento se aplica a todas las entregas de bienes y servicios realizados a este comprador en el periodo indicado.",
  "invoice.discount.notAll": "El descuento no se aplica a todas las entregas de bienes y servicios realizados a este comprador en el periodo indicado."
};

const IT = {
  "invoice.subject2.jst": "La fattura riguarda un'unita subordinata JST: ",
  "invoice.subject2.gv": "La fattura riguarda un membro del gruppo GV: ",
  "invoice.subject2.yes": "SI",
  "invoice.subject2.no": "NO",
  "invoice.registers.fullAccountNumber": "Numero completo del conto",
  "invoice.registers.fullNrbAccountNumber": "Numero completo del conto NRB",
  "invoice.registers.fullForeignAccountNumber": "Numero completo del conto estero",
  "invoice.registers.swiftCode": "Codice SWIFT",
  "invoice.registers.ownBankAccount": "Conto bancario proprio",
  "invoice.registers.bankName": "Nome della banca",
  "invoice.registers.accountDescription": "Descrizione del conto",
  "invoice.registers.header": "Registri",
  "invoice.discount.all": "Lo sconto si applica a tutte le cessioni di beni e prestazioni di servizi effettuate a favore di questo acquirente nel periodo indicato.",
  "invoice.discount.notAll": "Lo sconto non si applica a tutte le cessioni di beni e prestazioni di servizi effettuate a favore di questo acquirente nel periodo indicato."
};

const SUBJECT3_ROLE_OVERRIDES: Partial<Record<LanguageCode, Record<string, string>>> = {
  en: {
    "const.fa.factor": "Factor - where factor data appears on the invoice",
    "const.fa.recipient": "Recipient - where the invoice includes data of internal units or branches within the buyer that are not buyers within the meaning of the Act",
    "const.fa.primaryEntity": "Original entity - where the invoice includes data of an acquired or transformed entity that supplied goods or services",
    "const.fa.additionalBuyer": "Additional buyer - where the invoice contains data of further buyers other than the buyer listed in Podmiot2",
    "const.fa.invoiceIssuer": "Invoice issuer - where the invoice includes data of the entity issuing the invoice on behalf of the taxpayer",
    "const.fa.payer": "Payer - where the invoice includes data of the entity settling the obligation instead of the buyer",
    "const.fa.localGovernmentIssuer": "Local government unit - issuer",
    "const.fa.localGovernmentRecipient": "Local government unit - recipient",
    "const.fa.vatGroupIssuer": "VAT group member - issuer",
    "const.fa.vatGroupRecipient": "VAT group member - recipient",
    "const.fa.employee": "Employee"
  },
  de: {
    "const.fa.factor": "Factor - wenn die Rechnung Daten des Factors enthaelt",
    "const.fa.recipient": "Empfaenger - wenn die Rechnung Daten interner Einheiten oder Zweigstellen des Kaufers enthaelt, die selbst keine Kaufer im Sinne des Gesetzes sind",
    "const.fa.primaryEntity": "Urspruengliche Einheit - wenn die Rechnung Daten einer uebernommenen oder umgewandelten Einheit enthaelt, die Waren geliefert oder Dienstleistungen erbracht hat",
    "const.fa.additionalBuyer": "Weiterer Kaufer - wenn die Rechnung Daten weiterer Kaufer enthaelt, die nicht in Podmiot2 genannt sind",
    "const.fa.invoiceIssuer": "Rechnungsaussteller - wenn die Rechnung Daten der Einheit enthaelt, die die Rechnung im Namen des Steuerpflichtigen ausstellt",
    "const.fa.payer": "Zahlende Einheit - wenn die Rechnung Daten der Einheit enthaelt, die die Verpflichtung anstelle des Kaufers begleicht",
    "const.fa.localGovernmentIssuer": "Gebietskoerperschaft - Aussteller",
    "const.fa.localGovernmentRecipient": "Gebietskoerperschaft - Empfaenger",
    "const.fa.vatGroupIssuer": "Mitglied der MwSt.-Gruppe - Aussteller",
    "const.fa.vatGroupRecipient": "Mitglied der MwSt.-Gruppe - Empfaenger",
    "const.fa.employee": "Mitarbeiter"
  },
  fr: {
    "const.fa.factor": "Factor - lorsque la facture contient les donnees du factor",
    "const.fa.recipient": "Destinataire - lorsque la facture contient les donnees d'unites internes ou de succursales de l'acheteur qui ne sont pas elles-memes des acheteurs au sens de la loi",
    "const.fa.primaryEntity": "Entite initiale - lorsque la facture contient les donnees d'une entite reprise ou transformee qui a livre des biens ou fourni des services",
    "const.fa.additionalBuyer": "Acheteur supplementaire - lorsque la facture contient les donnees d'autres acheteurs que celui indique dans Podmiot2",
    "const.fa.invoiceIssuer": "Emetteur de la facture - lorsque la facture contient les donnees de l'entite qui emet la facture au nom du contribuable",
    "const.fa.payer": "Payeur - lorsque la facture contient les donnees de l'entite qui regle l'obligation a la place de l'acheteur",
    "const.fa.localGovernmentIssuer": "Collectivite territoriale - emetteur",
    "const.fa.localGovernmentRecipient": "Collectivite territoriale - destinataire",
    "const.fa.vatGroupIssuer": "Membre du groupe TVA - emetteur",
    "const.fa.vatGroupRecipient": "Membre du groupe TVA - destinataire",
    "const.fa.employee": "Employe"
  },
  es: {
    "const.fa.factor": "Factor - cuando la factura contiene datos del factor",
    "const.fa.recipient": "Destinatario - unidad interna o sucursal del comprador",
    "const.fa.primaryEntity": "Entidad original - entidad adquirida o transformada que suministro bienes o servicios",
    "const.fa.additionalBuyer": "Comprador adicional - cuando la factura contiene datos de otros compradores distintos del indicado en Podmiot2",
    "const.fa.invoiceIssuer": "Emisor de la factura - entidad que emite la factura en nombre del contribuyente",
    "const.fa.payer": "Pagador - entidad que liquida la obligacion en lugar del comprador",
    "const.fa.localGovernmentIssuer": "Entidad de gobierno local - emisor",
    "const.fa.localGovernmentRecipient": "Entidad de gobierno local - destinatario",
    "const.fa.vatGroupIssuer": "Miembro del grupo de IVA - emisor",
    "const.fa.vatGroupRecipient": "Miembro del grupo de IVA - destinatario",
    "const.fa.employee": "Empleado"
  },
  it: {
    "const.fa.factor": "Factor - quando la fattura contiene i dati del factor",
    "const.fa.recipient": "Destinatario - unita interna o filiale dell'acquirente",
    "const.fa.primaryEntity": "Entita originaria - entita acquisita o trasformata che ha fornito beni o servizi",
    "const.fa.additionalBuyer": "Acquirente aggiuntivo - quando la fattura contiene dati di altri acquirenti diversi da quello indicato in Podmiot2",
    "const.fa.invoiceIssuer": "Emittente della fattura - entita che emette la fattura per conto del contribuente",
    "const.fa.payer": "Pagatore - entita che salda l'obbligazione al posto dell'acquirente",
    "const.fa.localGovernmentIssuer": "Ente locale - emittente",
    "const.fa.localGovernmentRecipient": "Ente locale - destinatario",
    "const.fa.vatGroupIssuer": "Membro del gruppo IVA - emittente",
    "const.fa.vatGroupRecipient": "Membro del gruppo IVA - destinatario",
    "const.fa.employee": "Dipendente"
  },
  nl: {
    "const.fa.factor": "Factor - wanneer de factuur factorgegevens bevat",
    "const.fa.recipient": "Ontvanger - interne eenheid of filiaal van de koper",
    "const.fa.primaryEntity": "Oorspronkelijke entiteit - overgenomen of omgevormde entiteit die goederen of diensten leverde",
    "const.fa.additionalBuyer": "Extra koper - wanneer de factuur gegevens bevat van andere kopers dan de koper in Podmiot2",
    "const.fa.invoiceIssuer": "Factuuruitgever - entiteit die de factuur namens de belastingplichtige uitgeeft",
    "const.fa.payer": "Betaler - entiteit die de verplichting namens de koper voldoet",
    "const.fa.localGovernmentIssuer": "Lokale overheid - uitgever",
    "const.fa.localGovernmentRecipient": "Lokale overheid - ontvanger",
    "const.fa.vatGroupIssuer": "Lid van de btw-groep - uitgever",
    "const.fa.vatGroupRecipient": "Lid van de btw-groep - ontvanger",
    "const.fa.employee": "Werknemer"
  },
  pt: {
    "const.fa.factor": "Factor - quando a fatura contem dados do factor",
    "const.fa.recipient": "Destinatario - unidade interna ou sucursal do comprador",
    "const.fa.primaryEntity": "Entidade original - entidade adquirida ou transformada que forneceu bens ou servicos",
    "const.fa.additionalBuyer": "Comprador adicional - quando a fatura contem dados de outros compradores alem do indicado em Podmiot2",
    "const.fa.invoiceIssuer": "Emissor da fatura - entidade que emite a fatura em nome do contribuinte",
    "const.fa.payer": "Pagador - entidade que liquida a obrigacao em vez do comprador",
    "const.fa.localGovernmentIssuer": "Entidade de governo local - emissor",
    "const.fa.localGovernmentRecipient": "Entidade de governo local - destinatario",
    "const.fa.vatGroupIssuer": "Membro do grupo de IVA - emissor",
    "const.fa.vatGroupRecipient": "Membro do grupo de IVA - destinatario",
    "const.fa.employee": "Empregado"
  },
  cs: {
    "const.fa.factor": "Faktor - pokud faktura obsahuje udaje faktora",
    "const.fa.recipient": "Prijemce - vnitrni jednotka nebo pobocka kupujiciho",
    "const.fa.primaryEntity": "Puvodni subjekt - prevzaty nebo transformovany subjekt, ktery dodal zbozi nebo sluzby",
    "const.fa.additionalBuyer": "Dalsi kupujici - pokud faktura obsahuje udaje dalsich kupujicich mimo subjekt uvedeny v Podmiot2",
    "const.fa.invoiceIssuer": "Vystavitel faktury - subjekt vystavujici fakturu jmenem danoveho poplatnika",
    "const.fa.payer": "Platce - subjekt hradici zavazek misto kupujiciho",
    "const.fa.localGovernmentIssuer": "Mistni samosprava - vystavitel",
    "const.fa.localGovernmentRecipient": "Mistni samosprava - prijemce",
    "const.fa.vatGroupIssuer": "Clen skupiny DPH - vystavitel",
    "const.fa.vatGroupRecipient": "Clen skupiny DPH - prijemce",
    "const.fa.employee": "Zamestnanec"
  },
  sk: {
    "const.fa.factor": "Faktor - ak faktura obsahuje udaje faktora",
    "const.fa.recipient": "Prijemca - vnutorna jednotka alebo pobocka kupujuceho",
    "const.fa.primaryEntity": "Povodny subjekt - prevzaty alebo transformovany subjekt, ktory dodal tovar alebo sluzby",
    "const.fa.additionalBuyer": "Dalsi kupujuci - ak faktura obsahuje udaje dalsich kupujucich okrem subjektu uvedeneho v Podmiot2",
    "const.fa.invoiceIssuer": "Vystavitel faktury - subjekt vystavujuci fakturu v mene danovnika",
    "const.fa.payer": "Platca - subjekt hradzajuci zavazok namiesto kupujuceho",
    "const.fa.localGovernmentIssuer": "Miestna samosprava - vystavitel",
    "const.fa.localGovernmentRecipient": "Miestna samosprava - prijemca",
    "const.fa.vatGroupIssuer": "Clen skupiny DPH - vystavitel",
    "const.fa.vatGroupRecipient": "Clen skupiny DPH - prijemca",
    "const.fa.employee": "Zamestnanec"
  },
  hu: {
    "const.fa.factor": "Faktor - ha a szamla faktoradatokat tartalmaz",
    "const.fa.recipient": "Cimzett - a vevo belso egysege vagy fiokja",
    "const.fa.primaryEntity": "Eredeti szervezet - atvett vagy atalakitott szervezet, amely arut vagy szolgaltatast nyujtott",
    "const.fa.additionalBuyer": "Tovabbi vevo - ha a szamla a Podmiot2-ben megadotton kivuli vevok adatait tartalmazza",
    "const.fa.invoiceIssuer": "Szamla kiallitaja - a szamlat az adozo neveben kiallito szervezet",
    "const.fa.payer": "Fizeto - a kotelezettseget a vevo helyett rendezo szervezet",
    "const.fa.localGovernmentIssuer": "Onkormanyzati egyseg - kiallito",
    "const.fa.localGovernmentRecipient": "Onkormanyzati egyseg - cimzett",
    "const.fa.vatGroupIssuer": "Afacsoport tagja - kiallito",
    "const.fa.vatGroupRecipient": "Afacsoport tagja - cimzett",
    "const.fa.employee": "Munkavallalo"
  },
  ro: {
    "const.fa.factor": "Factor - cand factura contine datele factorului",
    "const.fa.recipient": "Destinatar - unitate interna sau sucursala a cumparatorului",
    "const.fa.primaryEntity": "Entitate initiala - entitate preluata sau transformata care a livrat bunuri sau servicii",
    "const.fa.additionalBuyer": "Cumparator suplimentar - cand factura contine datele altor cumparatori decat cel indicat in Podmiot2",
    "const.fa.invoiceIssuer": "Emitentul facturii - entitatea care emite factura in numele contribuabilului",
    "const.fa.payer": "Platitor - entitatea care achita obligatia in locul cumparatorului",
    "const.fa.localGovernmentIssuer": "Unitate administrativ-teritoriala - emitent",
    "const.fa.localGovernmentRecipient": "Unitate administrativ-teritoriala - destinatar",
    "const.fa.vatGroupIssuer": "Membru al grupului TVA - emitent",
    "const.fa.vatGroupRecipient": "Membru al grupului TVA - destinatar",
    "const.fa.employee": "Angajat"
  },
  bg: {
    "const.fa.factor": "Faktor - kogato fakturata sadarzha danni za faktora",
    "const.fa.recipient": "Poluchatel - vatreshno zveno ili klon na kupuvacha",
    "const.fa.primaryEntity": "Parvonachalen subekt - pridobit ili preobrazuvan subekt, dostavil stoki ili uslugi",
    "const.fa.additionalBuyer": "Dopalnitelen kupuvach - kogato fakturata sadarzha danni za drugi kupuvachi osven posocheniya v Podmiot2",
    "const.fa.invoiceIssuer": "Izdatel na fakturata - subekt, izdavasht fakturata ot imeto na danachno zadalzhenoto litse",
    "const.fa.payer": "Platets - subekt, koito plasha zadalzhenieto vmesto kupuvacha",
    "const.fa.localGovernmentIssuer": "Mestna vlast - izdatel",
    "const.fa.localGovernmentRecipient": "Mestna vlast - poluchatel",
    "const.fa.vatGroupIssuer": "Chlen na DDS grupa - izdatel",
    "const.fa.vatGroupRecipient": "Chlen na DDS grupa - poluchatel",
    "const.fa.employee": "Sluzhitel"
  },
  hr: {
    "const.fa.factor": "Faktor - kada racun sadrzi podatke faktora",
    "const.fa.recipient": "Primatelj - interna jedinica ili podruznica kupca",
    "const.fa.primaryEntity": "Izvorni subjekt - preuzeti ili preoblikovani subjekt koji je isporucio robu ili usluge",
    "const.fa.additionalBuyer": "Dodatni kupac - kada racun sadrzi podatke drugih kupaca osim onog navedenog u Podmiot2",
    "const.fa.invoiceIssuer": "Izdavatelj racuna - subjekt koji izdaje racun u ime poreznog obveznika",
    "const.fa.payer": "Platitelj - subjekt koji podmiruje obvezu umjesto kupca",
    "const.fa.localGovernmentIssuer": "Jedinica lokalne samouprave - izdavatelj",
    "const.fa.localGovernmentRecipient": "Jedinica lokalne samouprave - primatelj",
    "const.fa.vatGroupIssuer": "Clan PDV grupe - izdavatelj",
    "const.fa.vatGroupRecipient": "Clan PDV grupe - primatelj",
    "const.fa.employee": "Zaposlenik"
  },
  sl: {
    "const.fa.factor": "Faktor - kadar racun vsebuje podatke faktorja",
    "const.fa.recipient": "Prejemnik - notranja enota ali podruznica kupca",
    "const.fa.primaryEntity": "Prvotni subjekt - prevzeti ali preoblikovani subjekt, ki je dobavil blago ali storitve",
    "const.fa.additionalBuyer": "Dodatni kupec - kadar racun vsebuje podatke drugih kupcev poleg subjekta v Podmiot2",
    "const.fa.invoiceIssuer": "Izdajatelj racuna - subjekt, ki izda racun v imenu davcnega zavezanca",
    "const.fa.payer": "Placnik - subjekt, ki poravna obveznost namesto kupca",
    "const.fa.localGovernmentIssuer": "Lokalna samouprava - izdajatelj",
    "const.fa.localGovernmentRecipient": "Lokalna samouprava - prejemnik",
    "const.fa.vatGroupIssuer": "Clan skupine DDV - izdajatelj",
    "const.fa.vatGroupRecipient": "Clan skupine DDV - prejemnik",
    "const.fa.employee": "Zaposleni"
  },
  lt: {
    "const.fa.factor": "Faktorius - kai saskaitoje yra faktoriaus duomenys",
    "const.fa.recipient": "Gavejas - pirkejo vidinis padalinys arba filialas",
    "const.fa.primaryEntity": "Pradinis subjektas - perimtas arba pertvarkytas subjektas, tiekes prekes ar paslaugas",
    "const.fa.additionalBuyer": "Papildomas pirkejas - kai saskaitoje yra kitu pirkeju duomenys, ne tik nurodyto Podmiot2",
    "const.fa.invoiceIssuer": "Saskaitos israsejas - subjektas, israsantis saskaita mokesciu moketojo vardu",
    "const.fa.payer": "Moketojas - subjektas, apmokantis prievole vietoje pirkejo",
    "const.fa.localGovernmentIssuer": "Vietos savivaldos institucija - israsejas",
    "const.fa.localGovernmentRecipient": "Vietos savivaldos institucija - gavejas",
    "const.fa.vatGroupIssuer": "PVM grupes narys - israsejas",
    "const.fa.vatGroupRecipient": "PVM grupes narys - gavejas",
    "const.fa.employee": "Darbuotojas"
  },
  lv: {
    "const.fa.factor": "Faktors - ja rekina ir faktora dati",
    "const.fa.recipient": "Sanemejs - pirceja iekseja vieniba vai filiale",
    "const.fa.primaryEntity": "Sakotnejais subjekts - parnemts vai parveidots subjekts, kas piegadata preces vai pakalpojumus",
    "const.fa.additionalBuyer": "Papildu pircejs - ja rekina ir citu pirceju dati, kas nav noraditi Podmiot2",
    "const.fa.invoiceIssuer": "Rekina izdevejs - subjekts, kas izdod rekinu nodoklu maksataja varda",
    "const.fa.payer": "Maksatajs - subjekts, kas izpilda saistibas pirceja vieta",
    "const.fa.localGovernmentIssuer": "Vieteja pasvaldiba - izdevejs",
    "const.fa.localGovernmentRecipient": "Vieteja pasvaldiba - sanemejs",
    "const.fa.vatGroupIssuer": "PVN grupas dalibnieks - izdevejs",
    "const.fa.vatGroupRecipient": "PVN grupas dalibnieks - sanemejs",
    "const.fa.employee": "Darbinieks"
  },
  et: {
    "const.fa.factor": "Faktooringu osapool - kui arve sisaldab faktori andmeid",
    "const.fa.recipient": "Saaja - ostja siseyksus voi filiaal",
    "const.fa.primaryEntity": "Algne yksus - yle voetud voi ymber kujundatud yksus, mis tarnis kaupu voi teenuseid",
    "const.fa.additionalBuyer": "Lisaks ostja - kui arve sisaldab teiste ostjate andmeid peale Podmiot2-s nimetatu",
    "const.fa.invoiceIssuer": "Arve valjastaja - yksus, kes valjastab arve maksumaksja nimel",
    "const.fa.payer": "Maksja - yksus, kes tasub kohustuse ostja asemel",
    "const.fa.localGovernmentIssuer": "Kohalik omavalitsus - valjastaja",
    "const.fa.localGovernmentRecipient": "Kohalik omavalitsus - saaja",
    "const.fa.vatGroupIssuer": "Kaibemaksugrupi liige - valjastaja",
    "const.fa.vatGroupRecipient": "Kaibemaksugrupi liige - saaja",
    "const.fa.employee": "Tootaja"
  },
  da: {
    "const.fa.factor": "Factor - nar fakturaen indeholder factordata",
    "const.fa.recipient": "Modtager - intern enhed eller filial hos koberen",
    "const.fa.primaryEntity": "Oprindelig enhed - overtaget eller omdannet enhed, der leverede varer eller tjenester",
    "const.fa.additionalBuyer": "Yderligere kober - nar fakturaen indeholder data om andre kobere end den, der er angivet i Podmiot2",
    "const.fa.invoiceIssuer": "Fakturaudsteder - enhed, der udsteder fakturaen pa skatteyderens vegne",
    "const.fa.payer": "Betaler - enhed, der afvikler forpligtelsen i stedet for koberen",
    "const.fa.localGovernmentIssuer": "Lokal myndighed - udsteder",
    "const.fa.localGovernmentRecipient": "Lokal myndighed - modtager",
    "const.fa.vatGroupIssuer": "Medlem af momsgruppe - udsteder",
    "const.fa.vatGroupRecipient": "Medlem af momsgruppe - modtager",
    "const.fa.employee": "Medarbejder"
  },
  sv: {
    "const.fa.factor": "Faktor - nar fakturan innehaller faktordata",
    "const.fa.recipient": "Mottagare - intern enhet eller filial hos koparen",
    "const.fa.primaryEntity": "Ursprunglig enhet - overtaget eller ombildad enhet som levererade varor eller tjanster",
    "const.fa.additionalBuyer": "Ytterligare kopare - nar fakturan innehaller uppgifter om andra kopare an den som anges i Podmiot2",
    "const.fa.invoiceIssuer": "Fakturautstallare - enhet som utfardar fakturan for den skattskyldiges rakning",
    "const.fa.payer": "Betalare - enhet som reglerar forpliktelsen i stallet for koparen",
    "const.fa.localGovernmentIssuer": "Lokal myndighet - utstallare",
    "const.fa.localGovernmentRecipient": "Lokal myndighet - mottagare",
    "const.fa.vatGroupIssuer": "Medlem i momsgrupp - utstallare",
    "const.fa.vatGroupRecipient": "Medlem i momsgrupp - mottagare",
    "const.fa.employee": "Anstalld"
  },
  fi: {
    "const.fa.factor": "Faktori - kun lasku sisaltaa faktorointiosapuolen tiedot",
    "const.fa.recipient": "Vastaanottaja - ostajan sisainen yksikko tai sivuliike",
    "const.fa.primaryEntity": "Alkuperainen yksikko - hankittu tai muunnettu yksikko, joka toimitti tavaroita tai palveluja",
    "const.fa.additionalBuyer": "Lisakauppaja - kun lasku sisaltaa muiden ostajien tiedot kuin Podmiot2:ssa mainitun",
    "const.fa.invoiceIssuer": "Laskun laatija - yksikko, joka laatii laskun verovelvollisen puolesta",
    "const.fa.payer": "Maksaja - yksikko, joka maksaa velvoitteen ostajan sijasta",
    "const.fa.localGovernmentIssuer": "Paikallishallinnon yksikko - laatija",
    "const.fa.localGovernmentRecipient": "Paikallishallinnon yksikko - vastaanottaja",
    "const.fa.vatGroupIssuer": "ALV-ryhman jasen - laatija",
    "const.fa.vatGroupRecipient": "ALV-ryhman jasen - vastaanottaja",
    "const.fa.employee": "Tyontekija"
  },
  no: {
    "const.fa.factor": "Faktor - nar fakturaen inneholder faktordata",
    "const.fa.recipient": "Mottaker - intern enhet eller filial hos kjoperen",
    "const.fa.primaryEntity": "Opprinnelig enhet - overtatt eller omdannet enhet som leverte varer eller tjenester",
    "const.fa.additionalBuyer": "Ytterligere kjoper - nar fakturaen inneholder data om andre kjopere enn den som er angitt i Podmiot2",
    "const.fa.invoiceIssuer": "Fakturautsteder - enhet som utsteder fakturaen pa vegne av skattyteren",
    "const.fa.payer": "Betaler - enhet som gjor opp forpliktelsen i stedet for kjoperen",
    "const.fa.localGovernmentIssuer": "Lokal myndighet - utsteder",
    "const.fa.localGovernmentRecipient": "Lokal myndighet - mottaker",
    "const.fa.vatGroupIssuer": "Medlem av mva-gruppe - utsteder",
    "const.fa.vatGroupRecipient": "Medlem av mva-gruppe - mottaker",
    "const.fa.employee": "Ansatt"
  },
  el: {
    "const.fa.factor": "Factor - otan to timologio periechei stoicheia factor",
    "const.fa.recipient": "Paraliptis - esoteriki monada i ypokatastima tou agorasti",
    "const.fa.primaryEntity": "Archiki ontotita - ontotita pou apoktithike i metaschimatistike kai pareiche agatha i ypiresies",
    "const.fa.additionalBuyer": "Proshetos agorastis - otan to timologio periechei stoicheia allon agoraston ektos apo auton sto Podmiot2",
    "const.fa.invoiceIssuer": "Ekdotes timologiou - ontotita pou ekdidei to timologio gia logariasmo tou forologoumenou",
    "const.fa.payer": "Plirotis - ontotita pou exoflei tin ypoxreosi anti tou agorasti",
    "const.fa.localGovernmentIssuer": "Topiki aftodioikisi - ekdotis",
    "const.fa.localGovernmentRecipient": "Topiki aftodioikisi - paraliptis",
    "const.fa.vatGroupIssuer": "Melos omadas FPA - ekdotis",
    "const.fa.vatGroupRecipient": "Melos omadas FPA - paraliptis",
    "const.fa.employee": "Ypallilos"
  }
};

const CORRECTION_TYPE_OVERRIDES: Record<LanguageCode, Record<string, string>> = {
  en: {
    "const.farr.correctionOriginalDate": "Correction effective on the date the original invoice is recognized",
    "const.farr.correctionInvoiceDate": "Correction effective on the date the correcting invoice is issued",
    "const.fa.correctionOtherDate": "Correction effective on another date, including when different correcting invoice lines have different effective dates"
  },
  de: {
    "const.farr.correctionOriginalDate": "Korrektur mit Wirkung zum Datum der Erfassung der urspruenglichen Rechnung",
    "const.farr.correctionInvoiceDate": "Korrektur mit Wirkung zum Ausstellungsdatum der Korrekturrechnung",
    "const.fa.correctionOtherDate": "Korrektur mit Wirkung zu einem anderen Datum, auch wenn verschiedene Positionen der Korrekturrechnung unterschiedliche Daten haben"
  },
  fr: {
    "const.farr.correctionOriginalDate": "Correction prenant effet a la date de comptabilisation de la facture initiale",
    "const.farr.correctionInvoiceDate": "Correction prenant effet a la date d'emission de la facture corrective",
    "const.fa.correctionOtherDate": "Correction prenant effet a une autre date, y compris lorsque differentes lignes de la facture corrective ont des dates differentes"
  },
  es: {
    "const.farr.correctionOriginalDate": "Correccion efectiva en la fecha de registro de la factura original",
    "const.farr.correctionInvoiceDate": "Correccion efectiva en la fecha de emision de la factura rectificativa",
    "const.fa.correctionOtherDate": "Correccion efectiva en otra fecha, incluso cuando distintas lineas de la factura rectificativa tengan fechas diferentes"
  },
  it: {
    "const.farr.correctionOriginalDate": "Rettifica efficace alla data di registrazione della fattura originaria",
    "const.farr.correctionInvoiceDate": "Rettifica efficace alla data di emissione della fattura correttiva",
    "const.fa.correctionOtherDate": "Rettifica efficace in un'altra data, anche quando righe diverse della fattura correttiva hanno date diverse"
  },
  nl: {
    "const.farr.correctionOriginalDate": "Correctie van kracht op de datum waarop de oorspronkelijke factuur wordt geboekt",
    "const.farr.correctionInvoiceDate": "Correctie van kracht op de datum waarop de correctiefactuur wordt uitgegeven",
    "const.fa.correctionOtherDate": "Correctie van kracht op een andere datum, ook wanneer verschillende regels van de correctiefactuur verschillende datums hebben"
  },
  pt: {
    "const.farr.correctionOriginalDate": "Correcao com efeito na data de reconhecimento da fatura original",
    "const.farr.correctionInvoiceDate": "Correcao com efeito na data de emissao da fatura corretiva",
    "const.fa.correctionOtherDate": "Correcao com efeito noutra data, incluindo quando diferentes linhas da fatura corretiva tenham datas diferentes"
  },
  cs: {
    "const.farr.correctionOriginalDate": "Oprava ucinna k datu zauctovani puvodni faktury",
    "const.farr.correctionInvoiceDate": "Oprava ucinna k datu vystaveni opravne faktury",
    "const.fa.correctionOtherDate": "Oprava ucinna k jinemu datu, vcetne pripadu, kdy ruzne radky opravne faktury maji ruzna data"
  },
  sk: {
    "const.farr.correctionOriginalDate": "Oprava ucinna k datumu zauctovania povodnej faktury",
    "const.farr.correctionInvoiceDate": "Oprava ucinna k datumu vystavenia opravnej faktury",
    "const.fa.correctionOtherDate": "Oprava ucinna k inemu datumu, vratane pripadu, ked rozne riadky opravnej faktury maju rozne datumy"
  },
  hu: {
    "const.farr.correctionOriginalDate": "Helyesbites az eredeti szamla elszamolasanak datumaval hatalyos",
    "const.farr.correctionInvoiceDate": "Helyesbites a helyesbito szamla kiallitasi datumaval hatalyos",
    "const.fa.correctionOtherDate": "Helyesbites mas datumtol hatalyos, akkor is, ha a helyesbito szamla kulonbozo soraihoz kulonbozo datumok tartoznak"
  },
  ro: {
    "const.farr.correctionOriginalDate": "Corectie cu efect la data inregistrarii facturii initiale",
    "const.farr.correctionInvoiceDate": "Corectie cu efect la data emiterii facturii de corectie",
    "const.fa.correctionOtherDate": "Corectie cu efect la o alta data, inclusiv atunci cand linii diferite ale facturii de corectie au date diferite"
  },
  bg: {
    "const.farr.correctionOriginalDate": "Korektsiya s efekt kum datata na oschetovodyavane na parvonachalnata faktura",
    "const.farr.correctionInvoiceDate": "Korektsiya s efekt kum datata na izdavane na korektsionnata faktura",
    "const.fa.correctionOtherDate": "Korektsiya s efekt kum druga data, vklyuchitelno kogato razlichni redove na korektsionnata faktura imat razlichni dati"
  },
  hr: {
    "const.farr.correctionOriginalDate": "Ispravak koji vrijedi na datum knjizenja izvorne fakture",
    "const.farr.correctionInvoiceDate": "Ispravak koji vrijedi na datum izdavanja ispravne fakture",
    "const.fa.correctionOtherDate": "Ispravak koji vrijedi na drugi datum, ukljucujuci kada razlicite stavke ispravne fakture imaju razlicite datume"
  },
  sl: {
    "const.farr.correctionOriginalDate": "Popravek z ucinkom na datum knjizenja prvotnega racuna",
    "const.farr.correctionInvoiceDate": "Popravek z ucinkom na datum izdaje popravnega racuna",
    "const.fa.correctionOtherDate": "Popravek z ucinkom na drug datum, tudi kadar imajo razlicne vrstice popravnega racuna razlicne datume"
  },
  lt: {
    "const.farr.correctionOriginalDate": "Korekcija galioja pradines saskaitos pripazinimo diena",
    "const.farr.correctionInvoiceDate": "Korekcija galioja korekcines saskaitos israsymo diena",
    "const.fa.correctionOtherDate": "Korekcija galioja kita diena, iskaitant atvejus, kai skirtingos korekcines saskaitos eilutes turi skirtingas datas"
  },
  lv: {
    "const.farr.correctionOriginalDate": "Korekcija speka sakotneja rekina atzisanas datuma",
    "const.farr.correctionInvoiceDate": "Korekcija speka korekcijas rekina izdosanas datuma",
    "const.fa.correctionOtherDate": "Korekcija speka cita datuma, tostarp ja dazadam korekcijas rekina rindam ir dazadi datumi"
  },
  et: {
    "const.farr.correctionOriginalDate": "Parandus kehtib algse arve kajastamise kuupaeval",
    "const.farr.correctionInvoiceDate": "Parandus kehtib parandusarve valjastamise kuupaeval",
    "const.fa.correctionOtherDate": "Parandus kehtib muul kuupaeval, sealhulgas kui parandusarve eri ridadel on erinevad kuupaevad"
  },
  da: {
    "const.farr.correctionOriginalDate": "Korrektion med virkning pa datoen for registrering af den oprindelige faktura",
    "const.farr.correctionInvoiceDate": "Korrektion med virkning pa udstedelsesdatoen for korrektionsfakturaen",
    "const.fa.correctionOtherDate": "Korrektion med virkning pa en anden dato, ogsa nar forskellige linjer i korrektionsfakturaen har forskellige datoer"
  },
  sv: {
    "const.farr.correctionOriginalDate": "Korrigering som galler fran datumet da den ursprungliga fakturan bokfors",
    "const.farr.correctionInvoiceDate": "Korrigering som galler fran utfardandedatumet for korrigeringsfakturan",
    "const.fa.correctionOtherDate": "Korrigering som galler fran ett annat datum, aven nar olika rader i korrigeringsfakturan har olika datum"
  },
  fi: {
    "const.farr.correctionOriginalDate": "Korjaus voimassa alkuperaisen laskun kirjauspaivasta",
    "const.farr.correctionInvoiceDate": "Korjaus voimassa korjauslaskun laatimispaivasta",
    "const.fa.correctionOtherDate": "Korjaus voimassa muusta paivasta, myos kun korjauslaskun eri riveilla on eri paivamaarat"
  },
  no: {
    "const.farr.correctionOriginalDate": "Korreksjon med virkning fra datoen den opprinnelige fakturaen bokfores",
    "const.farr.correctionInvoiceDate": "Korreksjon med virkning fra utstedelsesdatoen for korrigeringsfakturaen",
    "const.fa.correctionOtherDate": "Korreksjon med virkning fra en annen dato, ogsa nar ulike linjer i korrigeringsfakturaen har ulike datoer"
  },
  el: {
    "const.farr.correctionOriginalDate": "Diorthosi me ischy apo tin imerominia katachorisis tou archikou timologiou",
    "const.farr.correctionInvoiceDate": "Diorthosi me ischy apo tin imerominia ekdosis tou diorthotikou timologiou",
    "const.fa.correctionOtherDate": "Diorthosi me ischy se alli imerominia, kai otan diaforetikes grammes tou diorthotikou timologiou echoun diaforetikes imerominies"
  }
};

const GENERATED: Record<LanguageCode, Record<string, string>> = {
  en: enGenerated,
  de: deGenerated,
  fr: frGenerated,
  es: esGenerated,
  it: itGenerated,
  nl: nlGenerated,
  pt: ptGenerated,
  cs: csGenerated,
  sk: skGenerated,
  hu: huGenerated,
  ro: roGenerated,
  bg: bgGenerated,
  hr: hrGenerated,
  sl: slGenerated,
  lt: ltGenerated,
  lv: lvGenerated,
  et: etGenerated,
  da: daGenerated,
  sv: svGenerated,
  fi: fiGenerated,
  no: noGenerated,
  el: elGenerated
};

export function getOfficialTextOverrides(language: LanguageCode): Record<string, string> {
  const fallback = language === "fr" ? FR : language === "de" ? DE : language === "es" ? ES : language === "it" ? IT : EN;
  return {
    ...fallback,
    ...GENERATED[language],
    ...SUBJECT3_ROLE_OVERRIDES[language],
    ...CORRECTION_TYPE_OVERRIDES[language],
    ...paymentMethodOverrides(language)
  };
}

function paymentMethodOverrides(language: LanguageCode) {
  return Object.fromEntries(
    Object.entries(PAYMENT_METHOD_OFFICIAL_KEYS).map(([code, key]) => [
      key,
      PAYMENT_METHOD_LABELS[language][code as keyof typeof PAYMENT_METHOD_OFFICIAL_KEYS]
    ])
  );
}
