import type { getLabels } from "@/lib/translation/dictionaries";
import type { LanguageCode } from "@/types/invoice";
import bgGenerated from "@/lib/mf-fa3/official-labels/generated/bg.json";
import csGenerated from "@/lib/mf-fa3/official-labels/generated/cs.json";
import daGenerated from "@/lib/mf-fa3/official-labels/generated/da.json";
import deGenerated from "@/lib/mf-fa3/official-labels/generated/de.json";
import elGenerated from "@/lib/mf-fa3/official-labels/generated/el.json";
import enGenerated from "@/lib/mf-fa3/official-labels/generated/en.json";
import esGenerated from "@/lib/mf-fa3/official-labels/generated/es.json";
import etGenerated from "@/lib/mf-fa3/official-labels/generated/et.json";
import fiGenerated from "@/lib/mf-fa3/official-labels/generated/fi.json";
import frGenerated from "@/lib/mf-fa3/official-labels/generated/fr.json";
import hrGenerated from "@/lib/mf-fa3/official-labels/generated/hr.json";
import huGenerated from "@/lib/mf-fa3/official-labels/generated/hu.json";
import itGenerated from "@/lib/mf-fa3/official-labels/generated/it.json";
import ltGenerated from "@/lib/mf-fa3/official-labels/generated/lt.json";
import lvGenerated from "@/lib/mf-fa3/official-labels/generated/lv.json";
import nlGenerated from "@/lib/mf-fa3/official-labels/generated/nl.json";
import noGenerated from "@/lib/mf-fa3/official-labels/generated/no.json";
import ptGenerated from "@/lib/mf-fa3/official-labels/generated/pt.json";
import roGenerated from "@/lib/mf-fa3/official-labels/generated/ro.json";
import skGenerated from "@/lib/mf-fa3/official-labels/generated/sk.json";
import slGenerated from "@/lib/mf-fa3/official-labels/generated/sl.json";
import svGenerated from "@/lib/mf-fa3/official-labels/generated/sv.json";

type AppLabelKey = keyof ReturnType<typeof getLabels>;

export const OFFICIAL_LABEL_MAP: Record<string, AppLabelKey> = {
  "invoice.header.invoiceNumberLabel": "invoiceNumber",
  "invoice.header.ksefNumberLabel": "ksefNumber",
  "invoice.header.vat": "invoiceTypeBasic",
  "invoice.header.advance": "invoiceTypeAdvance",
  "invoice.header.settlement": "invoiceTypeFinal",
  "invoice.header.correction": "invoiceTypeCorrection",
  "invoice.header.correctionCollective": "discountCorrection",
  "invoice.subject1.seller": "seller",
  "invoice.subject1.name": "seller",
  "invoice.subject1.address": "address",
  "invoice.subject1.nip": "vatId",
  "invoice.subject2.buyer": "buyer",
  "invoice.subject2.name": "buyer",
  "invoice.subject2.address": "address",
  "invoice.subject2.nip": "vatId",
  "invoice.subject3.otherEntity": "thirdParties",
  "invoice.authorizedSubject.authorizedSubject": "authorizedParty",
  "invoice.details.header": "details",
  "invoice.details.issueDate": "issueDateWithKsefClause",
  "invoice.details.issuePlace": "issuePlace",
  "invoice.details.discountPeriod": "discountPeriod",
  "invoice.details.deliveryOrServiceDate": "deliveryOrServiceDate",
  "invoice.details.deliveryOrServiceDateFrom": "servicePeriodFrom",
  "invoice.details.deliveryOrServiceDateTo": "servicePeriodTo",
  "invoice.details.getMoneyDate": "paymentReceivedDate",
  "invoice.details.currencyCode": "currencyCode",
  "invoice.details.commonCurrencyRate": "commonCurrencyRate",
  "invoice.details.currencyRate": "currencyRate",
  "invoice.details.ossProcedure": "ossProcedure",
  "invoice.details.advanceInvoiceNumbers": "advanceInvoices",
  "invoice.correctedInvoice.sectionHeader": "correctedInvoiceData",
  "invoice.correctedInvoice.invoiceNumber": "correctedInvoiceNumber",
  "invoice.correctedInvoice.correctionReason": "reason",
  "invoice.correctedInvoice.correctionEffectType": "correctionType",
  "invoice.rows.header": "rows",
  "invoice.rows.lp": "line",
  "invoice.rows.productName": "description",
  "invoice.rows.quantity": "quantity",
  "invoice.rows.unit": "unit",
  "invoice.rows.netUnitPrice": "unitPrice",
  "invoice.rows.grossUnitPrice": "grossValue",
  "invoice.rows.taxRate": "vatRate",
  "invoice.rows.netSalesValue": "netValue",
  "invoice.rows.grossSalesValue": "grossValue",
  "invoice.rows.vatSalesValue": "vatTotal",
  "invoice.rows.currencyRate": "currencyRate",
  "invoice.rows.index": "index",
  "invoice.rows.uniqueRowNumber": "uniqueRowNumber",
  "invoice.rows.discount": "discount",
  "invoice.rows.gtin": "gtin",
  "invoice.rows.pkwiu": "pkwiu",
  "invoice.rows.cn": "cn",
  "invoice.rows.pkob": "pkob",
  "invoice.rows.gtu": "gtu",
  "invoice.rows.procedure": "procedure",
  "invoice.rows.totalAmountDue": "grossTotal",
  "invoice.discount.header": "discountCorrection",
  "invoice.discount.lp": "line",
  "invoice.discount.productName": "description",
  "invoice.discount.quantity": "quantity",
  "invoice.discount.unit": "unit",
  "invoice.discount.totalValue": "totalValue",
  "invoice.order.productName": "description",
  "invoice.order.quantity": "quantity",
  "invoice.order.unit": "unit",
  "invoice.order.netUnitPrice": "unitPrice",
  "invoice.order.taxRate": "vatRate",
  "invoice.order.netSalesValue": "netValue",
  "invoice.order.taxAmount": "vatTotal",
  "invoice.order.currencyRate": "currencyRate",
  "invoice.order.orderNumber": "orderNumber",
  "invoice.order.totalAmountDue": "grossTotal",
  "invoice.summary.sectionHeader": "taxSummary",
  "invoice.summary.lp": "line",
  "invoice.summary.taxRate": "taxRate",
  "invoice.summary.netAmount": "netValue",
  "invoice.summary.taxAmount": "vatTotal",
  "invoice.summary.grossAmount": "grossValue",
  "invoice.summary.taxAmountPLN": "vatTotal",
  "invoice.annotations.header": "annotations",
  "invoice.annotations.partialPayMechanism": "splitPayment",
  "invoice.annotations.cashMethod": "cashAccounting",
  "invoice.annotations.reverseTax": "reverseCharge",
  "invoice.annotations.selfInvoice": "selfBilling",
  "invoice.annotations.threePartsSimplerMethod": "simplifiedTriangularProcedure",
  "invoice.annotations.marginProcedure": "marginProcedure",
  "invoice.annotations.noTaxBase": "taxExemption",
  "invoice.additionalInformation.additionalInformationLabel": "additionalInformation",
  "invoice.additionalInformation.additionalDescription": "additionalInformation",
  "invoice.additionalInformation.ordinalNumber": "line",
  "invoice.additionalInformation.rowNumber": "line",
  "invoice.additionalInformation.infoType": "key",
  "invoice.additionalInformation.infoContent": "value",
  "invoice.information.header": "additionalInformation",
  "invoice.information.invoiceFooter": "footer",
  "invoice.settlement.header": "settlements",
  "invoice.settlement.charges": "charges",
  "invoice.settlement.deductions": "deductions",
  "invoice.settlement.chargeReason": "reason",
  "invoice.settlement.deductionReason": "reason",
  "invoice.settlement.totalCharges": "totalCharges",
  "invoice.settlement.totalDeductions": "totalDeductions",
  "invoice.settlement.toPay": "amountToPay",
  "invoice.settlement.toSettle": "amountToSettle",
  "invoice.payment.payment": "payment",
  "invoice.payment.paymentInformation": "paymentInformation",
  "invoice.payment.maturityDate": "dueDate",
  "invoice.payment.paymentMethod": "method",
  "invoice.payment.paymentDate": "paidDate",
  "invoice.payment.bankAccountNumber": "accountNumber",
  "invoice.payment.factorsBankAccountNumber": "factorBankAccounts",
  "invoice.payment.conditionalDiscount": "conditionalDiscount",
  "invoice.payment.discountConditions": "discountConditions",
  "invoice.payment.discountAmount": "discountAmount",
  "invoice.registers.header": "registry",
  "invoice.registers.fullAccountNumber": "accountNumber",
  "invoice.registers.fullNrbAccountNumber": "accountNumber",
  "invoice.registers.fullForeignAccountNumber": "accountNumber",
  "invoice.registers.swiftCode": "swift",
  "invoice.registers.ownBankAccount": "bankAccount",
  "invoice.registers.bankName": "bankName",
  "invoice.registers.accountDescription": "accountDescription",
  "invoice.registers.fullName": "seller",
  "invoice.registers.polish": "bankAccount",
  "invoice.registers.foreign": "bankAccount",
  "invoice.transaction.header": "transactionTerms",
  "invoice.transaction.contract": "contracts",
  "invoice.transaction.contractDate": "contractDate",
  "invoice.transaction.contractNumber": "contractNumber",
  "invoice.transaction.order": "orders",
  "invoice.transaction.orderDate": "orderDate",
  "invoice.transaction.orderNumber": "orderNumber",
  "invoice.transaction.currency": "contractualCurrency",
  "invoice.transaction.rate": "contractualRate",
  "invoice.transaction.batchNumber": "batchNumbers",
  "invoice.transaction.deliveryTerms": "deliveryTerms",
  "invoice.transport.header": "transportType",
  "invoice.transport.type": "transportType",
  "invoice.transport.otherTypeDescription": "otherTypeDescription",
  "invoice.transport.cargoDescription": "cargoDescription",
  "invoice.transport.otherCargoDescription": "otherCargoDescription",
  "invoice.transport.packageUnit": "packageUnit",
  "invoice.transport.startDateTime": "transportStart",
  "invoice.transport.endDateTime": "transportEnd",
  "invoice.transport.shipFrom": "shipFrom",
  "invoice.transport.shipTo": "shipTo",
  "invoice.transport.intermediateAddress": "shipThrough",
  "invoice.carrier.carrier": "carrier",
  "invoice.additionalInformation.documentDate": "issueDate",
  "invoice.additionalInformation.documentNumber": "documentNumber",
  "invoice.additionalInformation.exciseTaxRefund": "exciseTaxRefund",
  "invoice.additionalInformation.fpLabel": "additionalInformation",
  "invoice.additionalInformation.informationContent": "value",
  "invoice.additionalInformation.ksefDocumentNumber": "ksefNumber",
  "invoice.additionalInformation.paymentDocuments": "payment",
  "invoice.additionalInformation.tpLabel": "relatedParty",
  "invoice.additionalInformation.typeOfInformation": "key",
  "invoice.address.apartmentNumber": "address",
  "invoice.address.communeName": "address",
  "invoice.address.countryName": "address",
  "invoice.address.districtName": "address",
  "invoice.address.GLN": "address",
  "invoice.address.houseNumber": "address",
  "invoice.address.postName": "address",
  "invoice.address.streetName": "address",
  "invoice.address.townName": "address",
  "invoice.address.voivodeshipName": "address",
  "invoice.address.zipCode": "address",
  "invoice.annotations.bodyNumber": "documentNumber",
  "invoice.annotations.airDelivery": "newTransportMeans",
  "invoice.annotations.antiques": "marginProcedure",
  "invoice.annotations.artPieces": "marginProcedure",
  "invoice.annotations.boatDelivery": "newTransportMeans",
  "invoice.annotations.chassisNumber": "documentNumber",
  "invoice.annotations.description": "description",
  "invoice.annotations.directiveLaw": "directiveBasis",
  "invoice.annotations.factoryNumber": "documentNumber",
  "invoice.annotations.frameNumber": "documentNumber",
  "invoice.annotations.hullNumber": "documentNumber",
  "invoice.annotations.landDelivery": "newTransportMeans",
  "invoice.annotations.law": "legalBasis",
  "invoice.annotations.newTransportsDelivery": "newTransportMeans",
  "invoice.annotations.newTransportType": "transportType",
  "invoice.annotations.noTaxBaseDocument": "legalBasis",
  "invoice.annotations.noTaxBaseDocument2": "directiveBasis",
  "invoice.annotations.noTaxBaseDocument3": "otherBasis",
  "invoice.annotations.otherLaw": "otherBasis",
  "invoice.annotations.transportApprovalDate": "issueDate",
  "invoice.annotations.transportBrand": "description",
  "invoice.annotations.transportColor": "description",
  "invoice.annotations.transportMileage": "quantity",
  "invoice.annotations.transportModel": "description",
  "invoice.annotations.transportProductionYear": "issueDate",
  "invoice.annotations.transportRegistrationNumber": "documentNumber",
  "invoice.annotations.transportType": "transportType",
  "invoice.annotations.travelAgencies": "marginProcedure",
  "invoice.annotations.usedGoods": "marginProcedure",
  "invoice.annotations.usePermissionDate": "issueDate",
  "invoice.annotations.vin": "documentNumber",
  "invoice.attachment.blockHeader": "attachments",
  "invoice.attachment.details": "details",
  "invoice.attachment.tableLabel": "attachments",
  "invoice.attachment.tableSummary": "taxSummary",
  "invoice.authorizedSubject.address": "address",
  "invoice.authorizedSubject.contactData": "additionalInformation",
  "invoice.authorizedSubject.correspondenceAddress": "address",
  "invoice.authorizedSubject.correspondenceAddress2": "address",
  "invoice.authorizedSubject.email": "additionalInformation",
  "invoice.authorizedSubject.eori": "vatId",
  "invoice.authorizedSubject.noTaxId": "vatId",
  "invoice.authorizedSubject.otherTaxId": "vatId",
  "invoice.authorizedSubject.phone": "additionalInformation",
  "invoice.authorizedSubject.role": "authorizedParty",
  "invoice.carrier.carrierAddress": "address",
  "invoice.correctedInvoice.correctInvoiceNumber": "correctedInvoiceNumber",
  "invoice.correctedInvoice.identificationHeader": "correctedInvoiceData",
  "invoice.correctedInvoice.identificationHeaderIndexed": "correctedInvoiceData",
  "invoice.correctedInvoice.issueDate": "issueDate",
  "invoice.correctedInvoice.ksefNumber": "ksefNumber",
  "invoice.details.assignKsefNumberDate": "issueDate",
  "invoice.details.costAmount": "amount",
  "invoice.details.currencyRate2": "currencyRate",
  "invoice.details.getDate": "issueDate",
  "invoice.details.getMoneyDate2": "paymentReceivedDate",
  "invoice.details.invoiceDate": "issueDate",
  "invoice.details.invoiceDateSentToKsef": "issueDate",
  "invoice.details.invoiceDateShort": "issueDate",
  "invoice.details.invoiceNumber": "invoiceNumber",
  "invoice.details.paymentReceivedDate": "paymentReceivedDate",
  "invoice.details.place": "issuePlace",
  "invoice.details.to": "servicePeriodTo",
  "invoice.footer.margin": "marginProcedure",
  "invoice.header.attachmentWarning": "attachments",
  "invoice.header.ksefPart1": "verification",
  "invoice.header.ksefPart2": "verification",
  "invoice.header.ksefPart3": "verification",
  "invoice.footer.generatedIn": "generatedAt",
  "invoice.header.correctedInvoiceVatRr": "invoiceTypeCorrection",
  "invoice.header.correctionAdvance": "invoiceTypeCorrection",
  "invoice.header.correctionSettlement": "invoiceTypeCorrection",
  "invoice.header.primalInvoiceVatRr": "invoiceTypeBasic",
  "invoice.header.simplified": "invoiceTypeBasic",
  "invoice.order.additionalInfo": "additionalInformation",
  "invoice.order.advancePaymentAmount": "amount",
  "invoice.order.advancePaymentAmountCorrection": "amount",
  "invoice.order.cn": "cn",
  "invoice.order.exciseTaxAmount": "amount",
  "invoice.order.gtin": "gtin",
  "invoice.order.gtu": "gtu",
  "invoice.order.index": "index",
  "invoice.order.issuedInCurrency": "currency",
  "invoice.order.lp": "line",
  "invoice.order.orderValueWithTax": "grossValue",
  "invoice.order.ossTaxRate": "taxRate",
  "invoice.order.pkob": "pkob",
  "invoice.order.pkwiu": "pkwiu",
  "invoice.order.procedure": "procedure",
  "invoice.order.procedureMarkings": "procedure",
  "invoice.order.productMarker": "productMarker",
  "invoice.order.receivedAdvance": "amount",
  "invoice.order.stateBefore": "stateBefore",
  "invoice.order.uniqueRowNumber": "uniqueRowNumber",
  "invoice.payment.description": "description",
  "invoice.payment.farmer": "bankAccount",
  "invoice.payment.getter": "buyer",
  "invoice.payment.ksefTransferId": "ksefNumber",
  "invoice.payment.moneylessLink": "paymentLink",
  "invoice.payment.noPayment": "noPayment",
  "invoice.payment.other": "method",
  "invoice.payment.otherPaymentDescription": "description",
  "invoice.payment.paidAllInParts": "paidAllInParts",
  "invoice.payment.paidInPart": "paidInPart",
  "invoice.payment.paidStatus": "paidStatus",
  "invoice.payment.partialPayment": "partialPayments",
  "invoice.payment.partialPaymentAmount": "amount",
  "invoice.payment.partialPaymentDate": "paidDate",
  "invoice.payment.paymentDescription": "description",
  "invoice.payment.paymentDifferent": "method",
  "invoice.payment.paymentInformationContinued": "paymentInformation",
  "invoice.payment.paymentMethod2": "method",
  "invoice.payment.paymentMethod3": "method",
  "invoice.payment.transfer": "method",
  "invoice.qr1.offline": "verification",
  "invoice.qr2.certificate": "verification",
  "invoice.qr2.description": "verificationLink",
  "invoice.qr2.header": "verification",
  "invoice.registers.bdo": "bdo",
  "invoice.registers.billFormat": "registry",
  "invoice.registers.krs": "krs",
  "invoice.registers.regon": "regon",
  "invoice.rows.additionalInfo": "additionalInformation",
  "invoice.rows.amount": "quantity",
  "invoice.rows.deliveryDate": "deliveryOrServiceDate",
  "invoice.rows.costZZP": "amount",
  "invoice.rows.exciseTaxAmount": "amount",
  "invoice.rows.getDate": "issueDate",
  "invoice.rows.getOrMakeDate": "deliveryOrServiceDate",
  "invoice.rows.farmProductCost": "amount",
  "invoice.rows.inWords": "amount",
  "invoice.rows.issuedInCurrency": "currency",
  "invoice.rows.lumpSumTaxRefund": "amount",
  "invoice.rows.name": "description",
  "invoice.rows.ossTaxRate": "taxRate",
  "invoice.rows.procedureMarkings": "procedure",
  "invoice.rows.productMarker": "productMarker",
  "invoice.rows.overallCost": "grossTotal",
  "invoice.rows.priceNoZZP": "netValue",
  "invoice.rows.qualityDesc": "description",
  "invoice.rows.remainingAmount": "amountToPay",
  "invoice.rows.stateBefore": "stateBefore",
  "invoice.rows.unitPrice": "unitPrice",
  "invoice.rows.valueZZP": "grossValue",
  "invoice.rows.wageZZP": "vatRate",
  "invoice.subject1.contactDetails": "additionalInformation",
  "invoice.subject1.contractorNumber": "customerNumber",
  "invoice.subject1.correspondenceAddress": "address",
  "invoice.subject1.eoriNumber": "vatId",
  "invoice.subject1.mailingAddress": "address",
  "invoice.subject1.taxpayerStatus": "vatId",
  "invoice.subject1.vatPrefix": "vatId",
  "invoice.subject1K.address": "address",
  "invoice.subject1K.contactDetails": "additionalInformation",
  "invoice.subject1K.contractorNumber": "customerNumber",
  "invoice.subject1K.correctedContent": "correctedInvoiceData",
  "invoice.subject1K.correctiveContent": "correctedInvoiceData",
  "invoice.subject1K.correspondenceAddress": "address",
  "invoice.subject1K.eoriNumber": "vatId",
  "invoice.subject1K.identificationData": "vatId",
  "invoice.subject1K.mailingAddress": "address",
  "invoice.subject1K.seller": "seller",
  "invoice.subject1K.taxpayerStatus": "vatId",
  "invoice.subject1K.vatPrefix": "vatId",
  "invoice.subject2.contactDetails": "additionalInformation",
  "invoice.subject2.correspondenceAddress": "address",
  "invoice.subject2.customerNumber": "customerNumber",
  "invoice.subject2.eoriNumber": "vatId",
  "invoice.subject2.getterId": "vatId",
  "invoice.subject2.internalId": "vatId",
  "invoice.subject2.mailingAddress": "address",
  "invoice.subject2.noId": "vatId",
  "invoice.subject2.noTaxId": "vatId",
  "invoice.subject2.taxIdOther": "vatId",
  "invoice.subject2.taxPayerStatus": "vatId",
  "invoice.subject2.vatPrefix": "vatId",
  "invoice.subject2.vatUeNumber": "vatId",
  "invoice.subject2k.address": "address",
  "invoice.subject2k.buyer": "buyer",
  "invoice.subject2k.buyerId": "vatId",
  "invoice.subject2k.clientNumber": "customerNumber",
  "invoice.subject2k.contactDetails": "additionalInformation",
  "invoice.subject2k.correctedContent": "correctedInvoiceData",
  "invoice.subject2k.correctiveContent": "correctedInvoiceData",
  "invoice.subject2k.correspondenceAddress": "address",
  "invoice.subject2k.eori": "vatId",
  "invoice.subject2k.identificationData": "vatId",
  "invoice.subject2k.mailingAddress": "address",
  "invoice.subject2k.taxPayerStatus": "vatId",
  "invoice.subject3.address": "address",
  "invoice.subject3.clientNumber": "customerNumber",
  "invoice.subject3.contactData": "additionalInformation",
  "invoice.subject3.correspondenceAddress": "address",
  "invoice.subject3.eori": "vatId",
  "invoice.subject3.getterId": "vatId",
  "invoice.subject3.internalId": "vatId",
  "invoice.subject3.name": "thirdParties",
  "invoice.subject3.nip": "vatId",
  "invoice.subject3.noTaxId": "vatId",
  "invoice.subject3.otherId": "vatId",
  "invoice.subject3.otherRole": "thirdParties",
  "invoice.subject3.otherTaxId": "vatId",
  "invoice.subject3.role": "thirdParties",
  "invoice.subject3.roleDescription": "description",
  "invoice.subject3.share": "amount",
  "invoice.subject3.vatUeNumber": "vatId",
  "invoice.subject3k.address": "address",
  "invoice.subject3k.clientNumber": "customerNumber",
  "invoice.subject3k.correctedContent": "correctedInvoiceData",
  "invoice.subject3k.correctiveContent": "correctedInvoiceData",
  "invoice.subject3k.correspondenceAddress": "address",
  "invoice.subject3k.eori": "vatId",
  "invoice.subject3k.getterId": "vatId",
  "invoice.subject3k.identificationData": "vatId",
  "invoice.subject3k.noTaxId": "vatId",
  "invoice.subject3k.otherEntity": "thirdParties",
  "invoice.subject3k.otherRole": "thirdParties",
  "invoice.subject3k.otherTaxId": "vatId",
  "invoice.subject3k.role": "thirdParties",
  "invoice.subject3k.share": "amount",
  "invoice.subjectContactData.e-mail": "additionalInformation",
  "invoice.subjectContactData.email": "additionalInformation",
  "invoice.subjectContactData.phone": "additionalInformation",
  "invoice.subjectIdentificationData.fullName": "seller",
  "invoice.subjectIdentificationData.internalId": "vatId",
  "invoice.subjectIdentificationData.name": "seller",
  "invoice.subjectIdentificationData.nameSurname": "seller",
  "invoice.subjectIdentificationData.nip": "vatId",
  "invoice.subjectIdentificationData.noId": "vatId",
  "invoice.subjectIdentificationData.tradeName": "seller",
  "invoice.summary.5": "taxRate",
  "invoice.summary.0domestic": "taxRate",
  "invoice.summary.0export": "taxRate",
  "invoice.summary.0long": "taxRate",
  "invoice.summary.0mid": "taxRate",
  "invoice.summary.0short": "taxRate",
  "invoice.summary.0wdt": "taxRate",
  "invoice.summary.23or22": "taxRate",
  "invoice.summary.4or3": "taxRate",
  "invoice.summary.8or7": "taxRate",
  "invoice.summary.margin": "marginProcedure",
  "invoice.summary.noTax": "taxExemption",
  "invoice.summary.npBasedArt100": "taxExemption",
  "invoice.summary.npExcludingArt100": "taxExemption",
  "invoice.summary.oss": "ossProcedure",
  "invoice.summary.reverseTax": "reverseCharge",
  "invoice.summary.taxFree": "taxExemption",
  "invoice.transaction.currencyAndRate": "contractualRate",
  "invoice.transport.dataHeader": "transportType",
  "invoice.transport.gln": "address",
  "invoice.transport.orderNumber": "orderNumber",
  "invoice.transport.otherCargo": "otherCargoDescription",
  "invoice.transport.otherType": "otherTypeDescription",
  "invoice.transport.shipmentHeader": "transportType",
  "invoice.upo.authorizationDocumentShortcut": "verification",
  "invoice.upo.complexId": "verification",
  "invoice.upo.contextAuthorizationId": "verification",
  "invoice.upo.contextType": "verification",
  "invoice.upo.documentInfo": "additionalInformation",
  "invoice.upo.documentRangeFrom": "servicePeriodFrom",
  "invoice.upo.documentRangeTo": "servicePeriodTo",
  "invoice.upo.documentsTotal": "quantity",
  "invoice.upo.eDocumentFormCode": "documentNumber",
  "invoice.upo.entityFullName": "seller",
  "invoice.upo.functionValueShortcut": "verification",
  "invoice.upo.internalId": "vatId",
  "invoice.upo.peppolId": "vatId",
  "invoice.upo.registeredInMF": "verification",
  "invoice.upo.sendMethod": "method",
  "invoice.upo.sessionReferenceNumber": "documentNumber",
  "invoice.upo.upoKsef": "verification",
  "invoice.upo.upoPage": "line",
  "invoice.upo.upoPageTotal": "quantity",
  "invoice.upo.vendorNIP": "vatId",
  "invoice.upo.xsdFileLogicName": "fileName",
  "invoice.upo.nip": "vatId",
  "invoice.wz.documentsHeader": "warehouseDocuments",
  "invoice.wz.number": "documentNumber",
  "invoice.attachment.header": "attachments",
  "invoice.attachment.description": "description",
  "invoice.attachment.key": "key",
  "invoice.attachment.value": "value",
  "invoice.qr1.header": "verification",
  "invoice.qr1.description": "verificationLink"
};

const EN = {
  "invoice.subject2.jst": "Invoice concerns a subordinate JST unit: ",
  "invoice.subject2.gv": "Invoice concerns a GV group member: ",
  "invoice.subject2.yes": "YES",
  "invoice.subject2.no": "NO",
  "invoice.annotations.noTaxDelivery": "Supply of goods or services exempt from tax",
  "invoice.annotations.vat22DocumentRequired": "VAT-22 document is required",
  "invoice.annotations.vat22DocumentNotRequired": "VAT-22 document is not required",
  "invoice.discount.all": "Discount applies to all supplies of goods and services made to this buyer in the given period.",
  "invoice.discount.notAll": "Discount does not apply to all supplies of goods and services made to this buyer in the given period.",
  "invoice.transaction.intermediaryDelivery": "Delivery made by an intermediary entity referred to in art. 22 sec. 2d of the VAT Act.",
  "invoice.qr1.header": "Verify that your invoice is in KSeF",
  "invoice.qr1.description": "Cannot scan the code from the image? Use the verification link to verify the invoice.",
  "invoice.registers.fullAccountNumber": "Full account number",
  "invoice.registers.fullNrbAccountNumber": "Full NRB account number",
  "invoice.registers.fullForeignAccountNumber": "Full foreign account number",
  "invoice.registers.swiftCode": "SWIFT code",
  "invoice.registers.ownBankAccount": "Own bank account",
  "invoice.registers.bankName": "Bank name",
  "invoice.registers.accountDescription": "Account description",
  "invoice.registers.header": "Registers"
};

const FR = {
  "invoice.subject2.jst": "La facture concerne une unite subordonnee JST : ",
  "invoice.subject2.gv": "La facture concerne un membre du groupe GV : ",
  "invoice.subject2.yes": "OUI",
  "invoice.subject2.no": "NON",
  "invoice.annotations.noTaxDelivery": "Livraison de biens ou prestation de services exoneree de taxe",
  "invoice.annotations.vat22DocumentRequired": "Le document VAT-22 est requis",
  "invoice.annotations.vat22DocumentNotRequired": "Le document VAT-22 n'est pas requis",
  "invoice.discount.all": "La remise concerne toutes les livraisons de biens et prestations de services effectuees pour cet acheteur pendant la periode indiquee.",
  "invoice.discount.notAll": "La remise ne concerne pas toutes les livraisons de biens et prestations de services effectuees pour cet acheteur pendant la periode indiquee.",
  "invoice.transaction.intermediaryDelivery": "Livraison effectuee par un intermediaire vise a l'art. 22, sec. 2d, de la loi sur la TVA.",
  "invoice.qr1.header": "Verifiez que votre facture se trouve dans KSeF",
  "invoice.qr1.description": "Impossible de scanner le code depuis l'image ? Utilisez le lien de verification pour verifier la facture.",
  "invoice.registers.fullAccountNumber": "Numero de compte complet",
  "invoice.registers.fullNrbAccountNumber": "Numero de compte NRB complet",
  "invoice.registers.fullForeignAccountNumber": "Numero de compte etranger complet",
  "invoice.registers.swiftCode": "Code SWIFT",
  "invoice.registers.ownBankAccount": "Compte bancaire propre",
  "invoice.registers.bankName": "Nom de la banque",
  "invoice.registers.accountDescription": "Description du compte",
  "invoice.registers.header": "Registres"
};

const DE = {
  "invoice.subject2.jst": "Die Rechnung betrifft eine untergeordnete JST-Einheit: ",
  "invoice.subject2.gv": "Die Rechnung betrifft ein Mitglied der GV-Gruppe: ",
  "invoice.subject2.yes": "JA",
  "invoice.subject2.no": "NEIN",
  "invoice.registers.fullAccountNumber": "Vollstandige Kontonummer",
  "invoice.registers.fullNrbAccountNumber": "Vollstandige NRB-Kontonummer",
  "invoice.registers.fullForeignAccountNumber": "Vollstandige auslandische Kontonummer",
  "invoice.registers.swiftCode": "SWIFT-Code",
  "invoice.registers.ownBankAccount": "Eigenes Bankkonto",
  "invoice.registers.bankName": "Bankname",
  "invoice.registers.accountDescription": "Kontobeschreibung",
  "invoice.registers.header": "Register",
  "invoice.discount.all": "Der Rabatt gilt fur alle Warenlieferungen und Dienstleistungen an diesen Kaufer im angegebenen Zeitraum.",
  "invoice.discount.notAll": "Der Rabatt gilt nicht fur alle Warenlieferungen und Dienstleistungen an diesen Kaufer im angegebenen Zeitraum."
};

const ES = {
  "invoice.subject2.jst": "La factura se refiere a una unidad subordinada JST: ",
  "invoice.subject2.gv": "La factura se refiere a un miembro del grupo GV: ",
  "invoice.subject2.yes": "SI",
  "invoice.subject2.no": "NO",
  "invoice.registers.fullAccountNumber": "Numero de cuenta completo",
  "invoice.registers.fullNrbAccountNumber": "Numero de cuenta NRB completo",
  "invoice.registers.fullForeignAccountNumber": "Numero de cuenta extranjera completo",
  "invoice.registers.swiftCode": "Codigo SWIFT",
  "invoice.registers.ownBankAccount": "Cuenta bancaria propia",
  "invoice.registers.bankName": "Nombre del banco",
  "invoice.registers.accountDescription": "Descripcion de la cuenta",
  "invoice.registers.header": "Registros",
  "invoice.discount.all": "El descuento se aplica a todas las entregas de bienes y servicios realizados a este comprador en el periodo indicado.",
  "invoice.discount.notAll": "El descuento no se aplica a todas las entregas de bienes y servicios realizados a este comprador en el periodo indicado."
};

const IT = {
  "invoice.subject2.jst": "La fattura riguarda un'unita subordinata JST: ",
  "invoice.subject2.gv": "La fattura riguarda un membro del gruppo GV: ",
  "invoice.subject2.yes": "SI",
  "invoice.subject2.no": "NO",
  "invoice.registers.fullAccountNumber": "Numero completo del conto",
  "invoice.registers.fullNrbAccountNumber": "Numero completo del conto NRB",
  "invoice.registers.fullForeignAccountNumber": "Numero completo del conto estero",
  "invoice.registers.swiftCode": "Codice SWIFT",
  "invoice.registers.ownBankAccount": "Conto bancario proprio",
  "invoice.registers.bankName": "Nome della banca",
  "invoice.registers.accountDescription": "Descrizione del conto",
  "invoice.registers.header": "Registri",
  "invoice.discount.all": "Lo sconto si applica a tutte le cessioni di beni e prestazioni di servizi effettuate a favore di questo acquirente nel periodo indicato.",
  "invoice.discount.notAll": "Lo sconto non si applica a tutte le cessioni di beni e prestazioni di servizi effettuate a favore di questo acquirente nel periodo indicato."
};

const GENERATED: Record<LanguageCode, Record<string, string>> = {
  en: enGenerated,
  de: deGenerated,
  fr: frGenerated,
  es: esGenerated,
  it: itGenerated,
  nl: nlGenerated,
  pt: ptGenerated,
  cs: csGenerated,
  sk: skGenerated,
  hu: huGenerated,
  ro: roGenerated,
  bg: bgGenerated,
  hr: hrGenerated,
  sl: slGenerated,
  lt: ltGenerated,
  lv: lvGenerated,
  et: etGenerated,
  da: daGenerated,
  sv: svGenerated,
  fi: fiGenerated,
  no: noGenerated,
  el: elGenerated
};

export function getOfficialTextOverrides(language: LanguageCode): Record<string, string> {
  const fallback = language === "fr" ? FR : language === "de" ? DE : language === "es" ? ES : language === "it" ? IT : EN;
  return { ...fallback, ...GENERATED[language] };
}
