/**
 * AUTO-GENERATED by scripts/generate-showcase-qr.mjs — do not edit by hand.
 *
 * Static QR matrix for the landing hero invoice. Encodes HTTPS://TLUMACZKSEF.PL
 * (uppercase keeps the code in alphanumeric mode -> version 1, 21x21 modules,
 * the smallest and therefore most scannable grid at the hero's 42px size).
 * Verified against the qrcode library in tests/lib/landing/showcase-qr.test.ts.
 */
import type { QRCodeErrorCorrectionLevel } from "qrcode";

export const SHOWCASE_QR_TEXT = "HTTPS://TLUMACZKSEF.PL";
export const SHOWCASE_QR_EC_LEVEL: QRCodeErrorCorrectionLevel = "L";
export const SHOWCASE_QR_SIZE = 21;

/** Row-major matrix; "1" is a dark module. */
export const SHOWCASE_QR_ROWS: readonly string[] = [
  "111111100010101111111",
  "100000101111101000001",
  "101110101011001011101",
  "101110100100101011101",
  "101110101111101011101",
  "100000101110001000001",
  "111111101010101111111",
  "000000001000100000000",
  "110100110011001110110",
  "010111000100011111111",
  "101010101000000010010",
  "011111010001010111001",
  "000101100011101100001",
  "000000001001110100011",
  "111111101011011010100",
  "100000100000110000001",
  "101110100101000100110",
  "101110101100010001011",
  "101110100111010100001",
  "100000101010000011001",
  "111111101100010100000"
];
